### PR TITLE
api: Accept unknown "emojiset" values in initial snapshot

### LINKED ISSUE #1981: Accept unknown "emojiset" values
The `Emojiset` enum, corresponding to the "emojiset" user setting (search for "emojiset" at https://zulip.com/api/register-queue ), accepts a handful of known values. If the server sends an unexpected value in register-queue, the app will reject it as malformed.

We might soon want to add a different value: [#api design > Using system emoji @ 💬](https://chat.zulip.org/#narrow/channel/378-api-design/topic/Using.20system.20emoji/near/2294848). It'd therefore be best if the app accepted unknown values for this setting.

We already don't act on the difference between three of the four possible values — we treat them all the same, and only distinguish the "text" value of the setting. If we see an unexpected value, it should be treated the same as the others apart from "text". (Effectively we'll be assuming that for any future API change that introduces a new value here, ignoring the new value and treating it the same as the current default/typical value will be better than refusing to act on that account at all.)

### Implementation

Use `JsonKey.unknownEnumValue`. Search the existing code for examples, and follow those examples.

### PR DESCRIPTION
**Pull request by MritunjayTiwari14**
Fixes #1981.

### CODE REVIEW

**Comment by chrisbobbe** [comment]
Let's make a new enum value `unknown` instead of using `google`.

**Comment by MritunjayTiwari14** [comment]
Thank you @chrisbobbe for the review, introduced a new enum value `unknown` to which all the unknow `Emojiset` are directed to.

File: test/api/model/initial_snapshot_test.dart [hunk 1]
```diff
@@ -62,4 +62,19 @@ void main() {
...
+    final unknownValues = ['apple', 'microsoft', 'facebook', ''];
+    for (final unknownValue in unknownValues) {
+      final settings = UserSettings.fromJson({
+        'twenty_four_hour_time': true,
+        'display_emoji_reaction_users': true,
+        'emojiset': unknownValue,
+        'presence_enabled': true,
+      });
+
+      // Verify unknown emojiset defaults to Emojiset.unknow
```
Comment (chrisbobbe) [inline test/api/model/initial_snapshot_test.dart]: nit: `Emojiset.unknown`

File: test/api/model/initial_snapshot_test.dart [hunk 2]
```diff
@@ -62,4 +62,19 @@ void main() {
...
+
+  test('UserSettings.emojiset handles various unknown values', () {
+    final unknownValues = ['apple', 'microsoft', 'facebook', ''];
+    for (final unknownValue in unknownValues) {
+      final settings = UserSettings.fromJson({
+        'twenty_four_hour_time': true,
+        'display_emoji_reaction_users': true,
+        'emojiset': unknownValue,
+        'presence_enabled': true,
+      });
```
Comment (chrisbobbe) [inline test/api/model/initial_snapshot_test.dart]: This `.fromJson` call will fail and need to be debugged each time we add a field to `UserSettings`.

Can you add a `userSettings` helper function in test/example_data.dart, on the pattern of similar helpers (like `streamMessage` or `initialSnapshot`), then I think this can just be

```suggestion
      final json = eg.userSettings().toJson()..['emojiset'] = unknownValue;
      final settings = UserSettings.fromJson(json);
```

**Comment by MritunjayTiwari14** [comment]
Thank you @chrisbobbe for the Suggestion, have pushed the changes. PTAL.

File: test/example_data.dart [hunk 3]
```diff
@@ -1304,6 +1304,20 @@ const _globalStore = globalStore;
...
+UserSettings userSettings({
+  TwentyFourHourTimeMode? twentyFourHourTime,
+  bool? displayEmojiReactionUsers,
+  Emojiset? emojiset,
+  bool? presenceEnabled,
+}) {
+  return UserSettings(
+    twentyFourHourTime: twentyFourHourTime ?? TwentyFourHourTimeMode.twentyFourHour,
+    displayEmojiReactionUsers: displayEmojiReactionUsers ?? true,
+    emojiset: emojiset ?? Emojiset.unknown ,
```
Comment (chrisbobbe) [inline test/example_data.dart]: We should aim to make the defaults boring and representative of real data, and I think `Emojiset.google` would be better for that than `Emojiset.unknown`.

Comment (chrisbobbe) [reply test/example_data.dart]: Also this helper can deduplicate some code in the `initialSnapshot` helper just below this.

Just below the `userSettings` function declaration, you can say

```dart
const _userSettings = userSettings;
```

then in `initialSnapshot` in choosing arguments for the `InitialSnapshot` constructor, you can say:

```dart
    userSettings: userSettings ?? _userSettings(),
```

**Review by chrisbobbe — COMMENTED** [review]
Thanks! Just small comments below.

Also something I just noticed on this round: for the commit-message summary line, let's say

```
api: Accept unknown "emojiset" values in initial snapshot
```

**Comment by MritunjayTiwari14** [comment]
Thank you @chrisbobbe for noticing that, I've also changed the value of `TwentyFourHourTimeMode.twentyFourHour` to default boring i.e `TwentyFourHourTimeMode.twelveHour`.

File: test/example_data.dart [hunk 4]
```diff
@@ -1304,6 +1304,22 @@ const _globalStore = globalStore;
...
+}) {
+  return UserSettings(
+    twentyFourHourTime: twentyFourHourTime ?? TwentyFourHourTimeMode.twelveHour,
+    displayEmojiReactionUsers: displayEmojiReactionUsers ?? true,
+    emojiset: emojiset ?? Emojiset.google,
+    presenceEnabled: presenceEnabled ?? true,
+  );
+}
+
+const _userSettings = userSettings;
```
Comment (chrisbobbe) [inline test/example_data.dart:1320]: nit: remove blank line above `const _userSettings = userSettings;`, following the pattern of other helpers in this file

**Comment by MritunjayTiwari14** [comment]
Thank you @chrisbobbe for the review, the new changes had been pushed. PTAL @gnprice.

File: lib/api/model/initial_snapshot.dart [hunk 5]
```diff
@@ -295,6 +295,7 @@ class UserSettings {
   TwentyFourHourTimeMode twentyFourHourTime;
 
   bool displayEmojiReactionUsers;
+  @JsonKey(unknownEnumValue: Emojiset.unknown)
   Emojiset emojiset;
```
Comment (gnprice) [inline lib/api/model/initial_snapshot.dart:299]: I looked at other references to `Emojiset` to see if we might need this elsewhere.

One is in events:
```dart
      case UserSettingName.emojiset:
        return Emojiset.fromRawString(value as String);
```

It looks like the effect of that is that if the user's value for this setting gets *changed* to an unknown value, we'd still throw. Let's fix that so that it produces `Emojiset.unknown`, just like if the same unknown value is found in the initial snapshot.

File: test/api/model/initial_snapshot_test.dart [hunk 6]
```diff
@@ -62,4 +63,15 @@ void main() {
...
   });
+
+  test('UserSettings.emojiset handles various unknown values', () {
+    final unknownValues = ['apple', 'microsoft', 'facebook', ''];
+    for (final unknownValue in unknownValues) {
+      final json = eg.userSettings().toJson()..['emojiset'] = unknownValue;
+      final settings = UserSettings.fromJson(json);
+
+      // Verify unknown emojiset defaults to Emojiset.unknown
+      check(settings.emojiset).equals(Emojiset.unknown);
```
Comment (gnprice) [inline test/api/model/initial_snapshot_test.dart]: This comment doesn't add anything that isn't said equally clearly by the code. So best to leave it out:
```suggestion
      check(settings.emojiset).equals(Emojiset.unknown);
```

File: test/api/model/initial_snapshot_test.dart [hunk 7]
```diff
@@ -62,4 +63,15 @@ void main() {
       'unread_message_ids': [11, 2, 3],
     })).throws<AssertionError>();
   });
+
+  test('UserSettings.emojiset handles various unknown values', () {
+    final unknownValues = ['apple', 'microsoft', 'facebook', ''];
+    for (final unknownValue in unknownValues) {
```
Comment (gnprice) [inline test/api/model/initial_snapshot_test.dart:69]: After the first of these, there's no useful information expressed by checking the next two — it's hard to imagine what sort of possible bug could be introduced in the future that would hit when the value were "microsoft" but not when it's "apple". So simplify the story by leaving them out:
```suggestion
  test('UserSettings.emojiset handles various unknown values', () {
    final unknownValues = ['apple', ''];
    for (final unknownValue in unknownValues) {
```

(OTOH the empty string does add information, since that's an edge case where it's more conceivable that there could be a bug specifically affecting that case.)

**Comment by MritunjayTiwari14** [comment]
Thank you @gnprice for the review, have applied the suggestion as described in the previous review, PTAL.

**Comment by MritunjayTiwari14** [comment]
Just saw that i have accidentally pushed the wrong changes, have updated them now. PTAL @gnprice.

File: pubspec.lock [hunk 8]
```diff
@@ -706,10 +706,10 @@ packages:
     dependency: transitive
     description:
       name: material_color_utilities
-      sha256: f7142bb1154231d7ea5f96bc7bde4bda2a0945d2806bb11670e30b850d56bdec
+      sha256: "9c337007e82b1889149c82ed242ed1cb24a66044e30979c44912381e9be4c48b"
       url: "https://pub.dev"
     source: hosted
-    version: "0.11.1"
+    version: "0.13.0"
```
Comment (gnprice) [inline pubspec.lock:688]: This change seems unrelated.

File: lib/api/model/model.dart [hunk 9]
```diff
@@ -390,13 +390,14 @@ enum Emojiset {
...
-  text;
+  text,
+  unknown;
 
   /// Get an [Emojiset] from a raw string. Throws if the string is unrecognized.
   ///
   /// Example:
   ///   'google-blob' -> Emojiset.googleBlob
-  static Emojiset fromRawString(String raw) => _byRawString[raw]!;
+  static Emojiset fromRawString(String raw) => _byRawString[raw] ?? unknown;
```
Comment (gnprice) [inline lib/api/model/model.dart:400]: Cool, this handles the other change I asked for at https://github.com/zulip/zulip-flutter/pull/1983#discussion_r2558427378 .

The commit message should then be updated so that it accurately covers what the commit now does:

    api: Accept unknown "emojiset" values in initial snapshot

as it's no longer just the initial snapshot.

**Review by gnprice — COMMENTED** [review]
Thanks! Small comments below; otherwise looks good.

**Comment by MritunjayTiwari14** [comment]
Thank you @gnprice for the Review, also hope that you had a great vacation. I have updated the commit message to remove the `in initial snapshot` to make it more general, PTAL.

**Comment by gnprice** [comment]
Thanks! Looks good; merging.
