### PR TITLE
button: Replace GestureDetector with Listener for `AnimatedScaleOnTap`

### LINKED ISSUE #1953: button: Delayed tap feedback on bottom nav and menu buttons
### Description
Mismatch in the animation behavior of home bottom nav bar icon button and Menu Page button
(Possibly issue is originating from `AnimatedScaleOnTap` in `button.dart`)

The Scale down and Scale up as well as Ink Splash animation occurs after a finite delay of [100ms](https://main-api.flutter.dev/flutter/gestures/kPressTimeout-constant.html). Mainly due to `GestureDetector` used inside `AnimatedScaleOnTap`.

> 
> /// The time that must elapse before a tap gesture sends onTapDown, if there's
> /// any doubt that the gesture is a tap.
> const Duration kPressTimeout = Duration(milliseconds: 100);

Discussion: [#mobile > issue in responsiveness of home bottom navbar icons](https://chat.zulip.org/#narrow/channel/48-mobile/topic/issue.20in.20responsiveness.20of.20home.20bottom.20navbar.20icons/with/2287111)
Design: [Figma Design](https://www.figma.com/design/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?node-id=2961-53767&t=mRzTcUA3JoTDsUTj-4)

### Steps to Reproduce
1. Go to Home Page
2. Click on any bottom navbar icon button
<br>

1. Go to Home Page
2. Further go to Menu Page
3. Click on any button

### Expected Behavior (Taken from Figma, Link to element is given in the top

https://github.com/user-attachments/assets/08d68c5a-b5d0-40a7-bc08-520f033dda5e

### Actual Behavior
https://github.com/user-attachments/assets/ffaf834b-7d2e-4924-89bb-db6b545bf93a

### Impact
Inconsistency between design and implementation, unexpected user experience.

### Possible Cause (Guess)
Already Specified in Description

### PR DESCRIPTION
**Pull request by MritunjayTiwari14**
Fixes #1953.

The Scale down and Scale up as well as Ink Splash animation occurs after a finite delay of [100ms](https://main-api.flutter.dev/flutter/gestures/kPressTimeout-constant.html). Mainly due to `GestureDetector` used inside `AnimatedScaleOnTap`. 

This can be fixed by using `Listener` hence replacing the `GestureDetector` inside `AnimatedScaleOnTap`.

Discussion: [#mobile > issue in responsiveness of home bottom navbar icons](https://chat.zulip.org/#narrow/channel/48-mobile/topic/issue.20in.20responsiveness.20of.20home.20bottom.20navbar.20icons/with/2287111)
Design: [Figma Design](https://www.figma.com/design/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?node-id=2961-53767&t=mRzTcUA3JoTDsUTj-4)

<details>
<summary>Comparison Through Video of Fix-up</summary>

### Before

https://github.com/user-attachments/assets/cc3c66a5-00cc-450c-88dc-6a6b9bb80d57

### After

https://github.com/user-attachments/assets/00fd4d59-564f-4041-9c19-03168a67de79

</details>

### CODE REVIEW

File: test/widgets/button_test.dart [hunk 1]
```diff
@@ -114,6 +114,39 @@ void main() {
       check(renderObject).size.equals(Size.square(40));
     });
 
+    group('AnimatedScaleOnTap', () {
+      void checkScale(WidgetTester tester, Finder finder, double expectedScale) {
+        final scale = tester.widget<AnimatedScale>(finder).scale;
+        check(scale).equals(expectedScale);
+      }
+
+      testWidgets('Animation happen instantly when tap down', (tester) async {
```
Comment (chrisbobbe) [inline test/widgets/button_test.dart]: When I run this test _without_ your change in lib/widgets/button.dart, it still passes. That means it's not doing its job.

File: lib/widgets/button.dart [hunk 2]
```diff
@@ -303,11 +303,11 @@ class _AnimatedScaleOnTapState extends State<AnimatedScaleOnTap> {
...
   Widget build(BuildContext context) {
-    return GestureDetector(
+    return Listener(
       behavior: HitTestBehavior.translucent,
-      onTapDown: (_) =>  _changeScale(widget.scaleEnd),
-      onTapUp: (_) =>    _changeScale(1),
-      onTapCancel: () => _changeScale(1),
+      onPointerDown: (_) =>  _changeScale(widget.scaleEnd),
+      onPointerUp: (_) =>    _changeScale(1),
+      onPointerCancel: (_) => _changeScale(1),
```
Comment (chrisbobbe) [inline lib/widgets/button.dart]: From reading the docs for [`GestureDetector.onTapDown`](https://main-api.flutter.dev/flutter/widgets/GestureDetector/onTapDown.html) and friends, it looks like one of the helpful features of that higher-level API is that it only considers pointer events from a "primary button". I don't know how common it is e.g. to use a stylus with multiple buttons, but this seems like functionality that would be helpful to keep.

The event passed to the `Listener.onPointerDown` callback (etc.) has a [`buttons` field](https://main-api.flutter.dev/flutter/gestures/PointerEvent/buttons.html). So in each of the handlers, let's check whether the event's `buttons` field equals [`kPrimaryButton`](https://main-api.flutter.dev/flutter/gestures/kPrimaryButton-constant.html), and only respond if it does.

Comment (chrisbobbe) [reply lib/widgets/button.dart]: Also, the name and dartdoc of this `AnimatedScaleOnTap` should be updated to match the new behavior: it's no longer about a tap gesture, which is only recognized after 100ms. For example:

```dart
/// Apply [Transform.scale] to the child widget on primary pointer-down,
/// and reset its scale on -up or -cancel, with animated transitions.
class AnimatedScaleOnPointerDown extends StatefulWidget {
```

**Review by chrisbobbe — COMMENTED** [review]
Thanks! Comments below.

**Comment by MritunjayTiwari14** [comment]
Thank you @chrisbobbe for the Review, added a timeout of 50 millisecond to pumpAndSettle to make sure in the test that animation happens almost instantly. Checked it with the previous code of button.dart that it failed, the updated code in button.dart as proposed in this PR does pass those test. PTAL.

File: lib/widgets/button.dart [hunk 3]
```diff
@@ -303,11 +305,20 @@ class _AnimatedScaleOnTapState extends State<AnimatedScaleOnTap> {
...
   @override
   Widget build(BuildContext context) {
-    return GestureDetector(
+    return Listener(
       behavior: HitTestBehavior.translucent,
-      onTapDown: (_) =>  _changeScale(widget.scaleEnd),
-      onTapUp: (_) =>    _changeScale(1),
-      onTapCancel: () => _changeScale(1),
+      onPointerDown: (PointerDownEvent pointerDownEvent) {
+        _pressedButton = pointerDownEvent.buttons;
```
Comment (chrisbobbe) [inline lib/widgets/button.dart]: Why store `.buttons` in a stateful variable? The events passed to `onPointerUp` and `onPointerCancel` have a `.buttons` field too, right; is there a reason not to instead just act on that data in the event?

File: test/widgets/button_test.dart [hunk 4]
```diff
@@ -114,6 +114,39 @@ void main() {
...
+              child: ZulipIconButton(
+                icon: ZulipIcons.follow,
+                onPressed: () {})))));
+        await tester.pump();
+
+        final animatedScaleFinder = find.byType(AnimatedScale);
+
+        // Now that the widget is being held down, its scale should be at the target scaleEnd i.e 0.95.
+        final gesture = await tester.startGesture(tester.getCenter(find.byType(ZulipIconButton)));
+        await tester.pumpAndSettle(const Duration(milliseconds: 50));
```
Comment (chrisbobbe) [inline test/widgets/button_test.dart]: Why `pumpAndSettle`? From its dartdoc:

```dart
  /// Repeatedly calls [pump] with the given `duration` until there are no
  /// longer any frames scheduled. This will call [pump] at least once, even if
  /// no frames are scheduled when the function is called, to flush any pending
  /// microtasks which may themselves schedule a frame.
```

The `AnimatedScale` should get set to 0.95 right away, right, and it handles the animation internally. How about:

```suggestion
        await tester.pump();
```

File: test/widgets/button_test.dart [hunk 5]
```diff
@@ -114,6 +114,39 @@ void main() {
...
+        checkScale(tester, animatedScaleFinder, 0.95);
+
+        // After releasing, the scale must return to 1.0.
+        await gesture.up();
+        await tester.pumpAndSettle();
```
Comment (chrisbobbe) [inline test/widgets/button_test.dart]:
```suggestion
        await tester.pump();
```

File: test/widgets/button_test.dart [hunk 6]
```diff
@@ -114,6 +114,39 @@ void main() {
...
+            duration: Duration(milliseconds: 100),
+            child: UnconstrainedBox(
+              child: ZulipIconButton(
+                icon: ZulipIcons.follow,
+                onPressed: () {})))));
+        await tester.pump();
+
+        final animatedScaleFinder = find.byType(AnimatedScale);
+
+        // Now that the widget is being held down, its scale should be at the target scaleEnd i.e 0.95.
```
Comment (chrisbobbe) [inline test/widgets/button_test.dart]: This comment doesn't add anything necessary that's not already clear from the code; let's remove it.

File: test/widgets/button_test.dart [hunk 7]
```diff
@@ -114,6 +114,39 @@ void main() {
...
+        final gesture = await tester.startGesture(tester.getCenter(find.byType(ZulipIconButton)));
+        await tester.pumpAndSettle(const Duration(milliseconds: 50));
+        checkScale(tester, animatedScaleFinder, 0.95);
+
+        // After releasing, the scale must return to 1.0.
```
Comment (chrisbobbe) [inline test/widgets/button_test.dart]: This comment can also be removed (same reasoning).

File: test/widgets/button_test.dart [hunk 8]
```diff
@@ -114,6 +114,39 @@ void main() {
...
+      }
+
+      testWidgets('Animation happen instantly when tap down', (tester) async {
+        addTearDown(testBinding.reset);
+
+        await tester.pumpWidget(TestZulipApp(
+          child: AnimatedScaleOnPrimaryPointerDown(
+            scaleEnd: 0.95,
+            duration: Duration(milliseconds: 100),
+            child: UnconstrainedBox(
```
Comment (chrisbobbe) [inline test/widgets/button_test.dart]: Is the `UnconstrainedBox` needed for the test? Seems like not, and the test would be simpler without it.

**Review by chrisbobbe — COMMENTED** [review]
Thanks! Comments below, from a human review. 🙂

I haven't been expecting Copilot AI to come along and give its feedback—I plan to discuss with Greg when he's back from his vacation. 🙂

File: lib/widgets/button.dart (hunk 3 above)
Comment (MritunjayTiwari14) [reply lib/widgets/button.dart]: The `PointerDownEvent` parameter is not accessible in other friends of `onPointerDown` function, since the type of the parameter and respective function differs. From its dartdoc:

 ```
  /// Called when a pointer comes into contact with the screen (for touch
  /// pointers), or has its button pressed (for mouse pointers) at this widget's
  /// location.
  final PointerDownEventListener? onPointerDown;

  ...

  /// Called when a pointer that triggered an [onPointerDown] is no longer in
  /// contact with the screen.
  final PointerUpEventListener? onPointerUp;
```

**Comment by MritunjayTiwari14** [comment]
Thank you @chrisbobbe for the review!, Yes I was also wonder about the Copilot AI feedback. Have pushed the changes, Please take a look!

File: lib/widgets/button.dart (hunk 3 above)
Comment (chrisbobbe) [reply lib/widgets/button.dart]: True, `onPointerUp` and `onPointerCancel` don't receive a `PointerDownEvent`. They do  receive a `PointerUpEvent` and a `PointerCancelEvent`, respectively, and both of those events have a [`.buttons` field (inherited from the base class `PointerEvent`, just like `PointerDownEvent.buttons`](https://api.flutter.dev/flutter/gestures/PointerEvent/buttons.html)).

**Review by chrisbobbe — COMMENTED** [review]
```
    button: Replace GestureDetector with Listener for `AnimatedScaleOnTap`
    
    Fixes #1953.
    Latter provides instant scaleDown animation on tap,
    unlike GestureDetector which has a `kPressTimeOut` causing
    delay of 100ms
      https://main-api.flutter.dev/flutter/gestures/kPressTimeout-constant.html
```

Commit-message nits:

- Empty line after the `Fixes` line.
- The text after that is redundant with the information in the `Fixes` line; let's delete it. (Also I noticed `kPressTimeOut` is misspelled there.)

See also: https://github.com/zulip/zulip-flutter/pull/1954#discussion_r2607915138

File: lib/widgets/button.dart (hunk 3 above)
Comment (MritunjayTiwari14) [reply lib/widgets/button.dart]: `buttons` is a bitmask of currently pressed buttons at the time of the event, not which button triggered the event. 

For eg. `pointerEventUp.buttons` represent the bit set of buttons currently pressed during the pointerUp Event not the button that was just released. Hence we don't require them in the first place, other than pointerDownEvent since we want to make sure the pointerDownEvent is initiated by kPrimaryButton.

For my investigation i found that the Dart Docs are bit [misleading](https://github.com/flutter/flutter/issues/110448#:~:text=(Desktop%20Triage)%20We%20think%20the%20problem%20here%20is%20one%20of%20documentation.%20The%20buttons%20field%20is%20meant%20to%20show%20the%20buttons%20that%20are%20currently%20pressed%2C%20and%20on%20button%20up%2C%20they%20are%20no%20longer%20pressed.%20We%20should%20probably%20document%20that%20more%20clearly.) for this method.

**Comment by MritunjayTiwari14** [comment]
Thank you @chrisbobbe for the Review, I have replied to the comment [#1954 (comment)](https://github.com/zulip/zulip-flutter/pull/1954#discussion_r2609559946) and updated the commit message. Will keep in mind to insert a new line between the `Fixes` line and the commit summary. Also have pushed new changes, PTAL!

File: lib/widgets/button.dart (hunk 3 above)
Comment (chrisbobbe) [reply lib/widgets/button.dart]: > For my investigation i found that the Dart Docs are bit [misleading](https://github.com/flutter/flutter/issues/110448#:~:text=(Desktop%20Triage)%20We%20think%20the%20problem%20here%20is%20one%20of%20documentation.%20The%20buttons%20field%20is%20meant%20to%20show%20the%20buttons%20that%20are%20currently%20pressed%2C%20and%20on%20button%20up%2C%20they%20are%20no%20longer%20pressed.%20We%20should%20probably%20document%20that%20more%20clearly.) for this method.

Interesting. The relevant doc is on the field on the base class: [`PointerEvent.buttons`](https://api.flutter.dev/flutter/gestures/PointerEvent/buttons.html):

```dart
  /// Bit field using the *Button constants such as [kPrimaryMouseButton],
  /// [kSecondaryStylusButton], etc.
  ///
  /// For example, if this has the value 6 and the
  /// [kind] is [PointerDeviceKind.invertedStylus], then this indicates an
  /// upside-down stylus with both its primary and secondary buttons pressed.
  final int buttons;
```

I guess the point is that it represents the set of buttons that are pressed at the time of the event: so when a button goes down, the `PointerDownEvent.buttons` will contain that button, and when that same button is released, the `PointerUpEvent.buttons` will _not_ contain the button. That seems coherent and usable, even if it's not the meaning I had originally expected (i.e. that `PointerUpEvent.buttons` would be the set of buttons that were released). We can shrink the child widget on a pointer-down event where `buttons` includes the primary button, and unshrink it on a pointer-up or pointer-cancel event where `buttons` does not include the primary button. Right?

File: lib/widgets/button.dart [hunk 9]
```diff
@@ -306,11 +307,13 @@ class _AnimatedScaleOnTapState extends State<AnimatedScaleOnTap> {
...
   @override
   Widget build(BuildContext context) {
-    return GestureDetector(
+    return Listener(
       behavior: HitTestBehavior.translucent,
-      onTapDown: (_) =>  _changeScale(widget.scaleEnd),
-      onTapUp: (_) =>    _changeScale(1),
-      onTapCancel: () => _changeScale(1),
+      onPointerDown: (PointerDownEvent pointerDownEvent) {
+        if((pointerDownEvent.buttons & kPrimaryButton) != 0) _changeScale(widget.scaleEnd);
```
Comment (chrisbobbe) [inline lib/widgets/button.dart]:
```suggestion
        if ((pointerDownEvent.buttons & kPrimaryButton) != 0) {
          _changeScale(widget.scaleEnd);
        }
```

**Review by chrisbobbe — COMMENTED** [review]
Thanks! One nit below, and I've responded above: https://github.com/zulip/zulip-flutter/pull/1954#discussion_r2620832675

File: lib/widgets/button.dart (hunk 3 above)
Comment (MritunjayTiwari14) [reply lib/widgets/button.dart]: Exactly, this must be done on `PointerUpEvent`. But i feel its not required for `PointerCancelEvent`, Since `PointerCancelEvent` is an abort signal, not a normal input event like down/move/up. So it should right away expand the widget to it's original size.

**Comment by MritunjayTiwari14** [comment]
Thank you @chrisbobbe for the Review, I have replied to your comment to the [#1954(comment)](https://github.com/zulip/zulip-flutter/pull/1954#discussion_r2623854741) and have pushed the new changes accordingly. PTAL!

File: lib/widgets/button.dart (hunk 3 above)
Comment (chrisbobbe) [reply lib/widgets/button.dart]: I see. Yes, I guess "pointer cancel" happens when the pointer moves outside the area covered by the child widget, and it makes sense that we should unshrink the child widget when this happens, even if the primary pointer button is down at the time.

**Comment by chrisbobbe** [comment]
Hmm, did you actually push the revision you intended? Bump on the above items:

- https://github.com/zulip/zulip-flutter/pull/1954#discussion_r2620836852
- https://github.com/zulip/zulip-flutter/pull/1954#discussion_r2623854741

**Comment by MritunjayTiwari14** [comment]
Thank you @chrisbobbe for noticing that, I've added the changes but did not commit them before the push. I've pushed the new changes now correctly. PTAL.

File: lib/widgets/button.dart [hunk 10]
```diff
@@ -306,11 +307,19 @@ class _AnimatedScaleOnTapState extends State<AnimatedScaleOnTap> {
...
-      onTapDown: (_) =>  _changeScale(widget.scaleEnd),
-      onTapUp: (_) =>    _changeScale(1),
-      onTapCancel: () => _changeScale(1),
+      onPointerDown: (PointerDownEvent pointerDownEvent) {
+        if ((pointerDownEvent.buttons & kPrimaryButton) != 0) {
+          _changeScale(widget.scaleEnd);
+        }
+      },
+      onPointerUp: (PointerUpEvent pointerUpEvent) {
+        if((pointerUpEvent.buttons & kPrimaryButton) == 0) {
```
Comment (chrisbobbe) [inline lib/widgets/button.dart]: Similar comment as https://github.com/zulip/zulip-flutter/pull/1954#discussion_r2620836852 :

```suggestion
        if ((pointerUpEvent.buttons & kPrimaryButton) == 0) {
```

Please try to catch this kind of detail in your self-review; it saves maintainers' time.

Comment (chrisbobbe) [reply lib/widgets/button.dart]: This is probably worth a quick explanatory comment; something like

```dart
// `.buttons` are the buttons immediately after the action that caused the event.
// When the primary button is up, the button should be full-size (scale 1).
```

File: test/widgets/button_test.dart [hunk 11]
```diff
@@ -114,6 +114,37 @@ void main() {
       check(renderObject).size.equals(Size.square(40));
     });
 
+    group('AnimatedScaleOnPrimaryPointerDown', () {
+      void checkScale(WidgetTester tester, Finder finder, double expectedScale) {
+        final scale = tester.widget<AnimatedScale>(finder).scale;
+        check(scale).equals(expectedScale);
+      }
+
+      testWidgets('Animation happen instantly when pointer down', (tester) async {
```
Comment (chrisbobbe) [inline test/widgets/button_test.dart]:
```suggestion
      testWidgets('Animation happens instantly on pointer down and up', (tester) async {
```

**Review by chrisbobbe — COMMENTED** [review]
Thanks! Small comments below.

File: lib/widgets/button.dart (hunk 10 above)
Comment (MritunjayTiwari14) [reply lib/widgets/button.dart]: That if conditional things happens mostly because I use C++ a lot sideways along with Dart and It get intermingled sometimes. Will make sure to follow self review throughly so it do not happens again.

**Comment by MritunjayTiwari14** [comment]
Thank you @chrisbobbe for the Review, Pushed some changes. PTAL.

File: lib/widgets/button.dart [hunk 12]
```diff
@@ -306,11 +307,23 @@ class _AnimatedScaleOnTapState extends State<AnimatedScaleOnTap> {
...
+
+      // `.buttons` are the pointer buttons which are pressed
+      // immediately after the action that caused the event.
+      // When the primary button is up, the button should be full-size (scale 1).
+      onPointerUp: (PointerUpEvent pointerUpEvent) {
+        if ((pointerUpEvent.buttons & kPrimaryButton) == 0) {
+          _changeScale(1);
+        }
+      },
+      onPointerCancel: (_) => _changeScale(1),
```
Comment (chrisbobbe) [inline lib/widgets/button.dart]: nit: put the explanatory comment closer to the code that makes it necessary, and remove "(scale 1)" because it doesn't add anything that's not already obvious. 

Also here's a comment that might help readers who wonder why we ignore the event param in `onPointerCancel` (like I did just before https://github.com/zulip/zulip-flutter/pull/1954#discussion_r2624504270 ):

```suggestion
      onPointerDown: (PointerDownEvent pointerDownEvent) {
        if ((pointerDownEvent.buttons & kPrimaryButton) != 0) {
          _changeScale(widget.scaleEnd);
        }
      },
      onPointerUp: (PointerUpEvent pointerUpEvent) {
        if ((pointerUpEvent.buttons & kPrimaryButton) == 0) {
          // `.buttons` are the pointer buttons which are pressed
          // immediately after the action that caused the event.
          // When the primary button is up, the child widget should be full-size.
          _changeScale(1);
        }
      },
      onPointerCancel: (_) {
        // The pointer is out of the child widget's bounds;
        // the child should be full-size even if the primary pointer is down.
        _changeScale(1);
      },
```

File: test/widgets/button_test.dart (hunk 8 above)
Comment (chrisbobbe) [reply test/widgets/button_test.dart]: bump on https://github.com/zulip/zulip-flutter/pull/1954#discussion_r2652031508

**Review by chrisbobbe — COMMENTED** [review]
Thanks! Comments below.

**Comment by MritunjayTiwari14** [comment]
Thank you @chrisbobbe for the Review, Pushed the Changes as requested. PTAL!

File: test/widgets/button_test.dart [hunk 13]
```diff
@@ -114,6 +114,36 @@ void main() {
       check(renderObject).size.equals(Size.square(40));
     });
 
+    group('AnimatedScaleOnPrimaryPointerDown', () {
```
Comment (chrisbobbe) [inline test/widgets/button_test.dart]: You've put this new group of tests inside the existing group called 'ZulipIconButton'. But `ZulipIconButton` and `AnimatedScaleOnPrimaryPointerDown` are separate, independent widgets, each with its own interface. Please un-nest this group from the 'ZulipIconButton' group.

File: test/widgets/button_test.dart [hunk 14]
```diff
@@ -114,6 +114,36 @@ void main() {
...
+            scaleEnd: 0.95,
+            duration: Duration(milliseconds: 100),
+            child: ZulipIconButton(
+              icon: ZulipIcons.follow,
+              onPressed: () {}))));
+        await tester.pump();
+
+        final animatedScaleFinder = find.byType(AnimatedScale);
+
+        final gesture = await tester.startGesture(tester.getCenter(find.byType(ZulipIconButton)));
```
Comment (chrisbobbe) [inline test/widgets/button_test.dart]: It looks like `tester.startGesture` has convenient parameters for controlling which buttons are involved in the gesture. Could you add a test that's much like this one except that the _secondary_ button is used, and checks that the child widget doesn't shrink?

File: lib/widgets/button.dart [hunk 15]
```diff
@@ -306,11 +307,26 @@ class _AnimatedScaleOnTapState extends State<AnimatedScaleOnTap> {
...
+          // immediately after the action that caused the event.
+          // When the primary button is up, the button should be full-size.
+          _changeScale(1);
+        }
+      },
+      onPointerCancel: (_) {
+        // The pointer is out of the child widget's bounds;
+        // the child should be full-size even if the primary pointer is down.
+        _changeScale(1);
+      },
```
Comment (chrisbobbe) [inline lib/widgets/button.dart:343]: Please add a test for this logic.

**Review by chrisbobbe — COMMENTED** [review]
Thanks! Comments below, including some things I missed in previous rounds.

**Comment by MritunjayTiwari14** [comment]
Thanks @chrisbobbe for the review. I have added some nits in this commit as they were required as a part of the update introduced as per the recent suggestion. PTAL.

File: test/widgets/button_test.dart [hunk 16]
```diff
@@ -116,4 +117,56 @@ void main() {
...
+    Future<void> prepare(WidgetTester tester) async {
+      addTearDown(testBinding.reset);
+
+      await tester.pumpWidget(TestZulipApp(
+          child: AnimatedScaleOnPrimaryPointerDown(
+              scaleEnd: 0.95,
+              duration: Duration(milliseconds: 100),
+              child: ZulipIconButton(
+                  icon: ZulipIcons.follow,
+                  onPressed: () {}))));
```
Comment (chrisbobbe) [inline test/widgets/button_test.dart]: nit: fix indentation

File: test/widgets/button_test.dart [hunk 17]
```diff
@@ -116,4 +117,56 @@ void main() {
...
+
+      await gesture.up();
+      await tester.pump();
+      checkAnimatedScale(tester, 1.0);
+    });
+
+    testWidgets('Animation does not happen when secondary pointer is down', (tester) async {
+      await prepare(tester);
+
+      await tester.startGesture(tester.getCenter(find.byType(ZulipIconButton)), buttons: kSecondaryButton);
```
Comment (chrisbobbe) [inline test/widgets/button_test.dart]: nit: split onto multiple lines (important information too far to the right)

File: test/widgets/button_test.dart [hunk 18]
```diff
@@ -116,4 +117,56 @@ void main() {
...
+                  onPressed: () {}))));
+      await tester.pump();
+    }
+
+    void checkAnimatedScale(WidgetTester tester, double expectedScale) {
+      final scale = tester.widget<AnimatedScale>(find.byType(AnimatedScale)).scale;
+      check(scale).equals(expectedScale);
+    }
+
+    testWidgets('Animation happen instantly when primary pointer down', (tester) async {
```
Comment (chrisbobbe) [inline test/widgets/button_test.dart]: nit: "happens"

File: lib/widgets/button.dart [hunk 19]
```diff
@@ -273,10 +274,10 @@ class ZulipIconButton extends StatelessWidget {
   }
 }
 
-/// Apply [Transform.scale] to the child widget when tapped, and reset its scale
-/// when released, while animating the transitions.
-class AnimatedScaleOnTap extends StatefulWidget {
-  const AnimatedScaleOnTap({
+/// Apply [Transform.scale] to the child widget on primary pointer-down,
+/// and reset its scale on -up or -cancel, with animated transitions.
+class AnimatedScaleOnPrimaryPointerDown extends StatefulWidget {
```
Comment (gnprice) [inline lib/widgets/button.dart]: This new name is long, and feels fairly technical ("primary pointer") about the details of how this widget is implemented. I'd like to give it a name that's focused instead on what one is thinking when looking at code that uses the widget.

I think a good name would be AnimatedScaleOnPress. From the perspective of code that uses this, the point is that this scales whenever the user is pressing on it.

Comment (gnprice) [reply lib/widgets/button.dart]: nit: Separately, the commit message uses the name AnimatedScaleOnTap, which is out of date as of this commit.

File: lib/widgets/button.dart [hunk 20]
```diff
@@ -306,11 +307,26 @@ class _AnimatedScaleOnTapState extends State<AnimatedScaleOnTap> {
...
   @override
   Widget build(BuildContext context) {
-    return GestureDetector(
+    return Listener(
       behavior: HitTestBehavior.translucent,
-      onTapDown: (_) =>  _changeScale(widget.scaleEnd),
-      onTapUp: (_) =>    _changeScale(1),
-      onTapCancel: () => _changeScale(1),
+      onPointerDown: (PointerDownEvent pointerDownEvent) {
+        if ((pointerDownEvent.buttons & kPrimaryButton) != 0) {
```
Comment (gnprice) [inline lib/widgets/button.dart]: nit: omit boring types; also there's no other event here which this could get confused with, so the simpler name "event" suffices:
```suggestion
      onPointerDown: (event) {
        if ((event.buttons & kPrimaryButton) != 0) {
```

File: test/widgets/button_test.dart [hunk 21]
```diff
@@ -116,4 +117,56 @@ void main() {
...
+    });
+
+    testWidgets('Scale reset when pointer cancel event occur', (tester) async {
+      await prepare(tester);
+
+      final gesture = await tester.startGesture(tester.getCenter(find.byType(ZulipIconButton)));
+      await tester.pump();
+      checkAnimatedScale(tester, 0.95);
+
+      await gesture.cancel();
```
Comment (gnprice) [inline test/widgets/button_test.dart:168]: Can you write a test for the scenario where the user starts pressing on the button, then drags their finger away? I think that's the most common way for a button tap gesture to get canceled.

**Comment by MritunjayTiwari14** [comment]
Thank you @gnprice and @chrisbobbe for the insightful review and quick response from Greg. 

As per [flutter maintainers](https://github.com/flutter/flutter/issues/93683).  `Listener` does not support any predefined type of method to detect whether the pointer is out of bound of the widget geometry unlike `GestureDetector` . I have implemented them using localPosition of the pointer itself. Which gets executed within constant Time Complexity/O(1).

Implemented the test for the same. PTAL Greg.

<details>
  <summary>Video of the Implementation</summary>
  <br>

  [scale_test_move_outside.webm](https://github.com/user-attachments/assets/810dc292-6c70-48fb-a804-543005002462)

</details>

File: test/widgets/button_test.dart [hunk 22]
```diff
@@ -116,4 +117,70 @@ void main() {
 
     // TODO test that the touch feedback fills the whole square
   });
+
+  group('AnimatedScaleOnPrimaryPointerDown', () {
```
Comment (gnprice) [inline test/widgets/button_test.dart]: nit: update name

In general any time you're renaming something, it's a good idea to do a grep afterward for any surviving instances of the old name.

Here, I did `git log --stat -p origin..` (see [my "secret" to using `git log`](https://github.com/zulip/zulip-mobile/blob/main/docs/howto/git.md#git-log-secret)), hit `/` to search, and entered `onprim` as a quick-to-type substring (case-insensitive) of the old name. That found this line.

Another effective way to search would have been `git grep AnimatedScaleOnPrimaryPointerDown`.

File: lib/widgets/button.dart [hunk 23]
```diff
@@ -304,14 +307,53 @@ class _AnimatedScaleOnTapState extends State<AnimatedScaleOnTap> {
     });
   }
 
+  void _checkBounds(PointerEvent event) {
+    final RenderBox? box = _targetKey.currentContext?.findRenderObject() as RenderBox?;
```
Comment (gnprice) [inline lib/widgets/button.dart]: How about just this:
```suggestion
    final RenderBox? box = context.findRenderObject() as RenderBox?;
```

Seems like the AnimatedScale (which this key points to) and this widget itself should have the same box, since the AnimatedScale just gets wrapped in a Listener, which proxies its child for layout.

Comment (gnprice) [reply lib/widgets/button.dart]: Also, omit boring types: just `final box = …`.

File: lib/widgets/button.dart [hunk 24]
```diff
@@ -304,14 +307,53 @@ class _AnimatedScaleOnTapState extends State<AnimatedScaleOnTap> {
...
+    if (box == null) return;
+
+    final Offset localPosition = box.globalToLocal(event.position);
+    final bool isOutside = localPosition.dx < 0 || localPosition.dy < 0 ||
+      localPosition.dy > box.size.height ||
+      localPosition.dx > box.size.width;
```
Comment (gnprice) [inline lib/widgets/button.dart]: This is a very standard question to ask, so look for a standard method to express it. Here, it looks like you want `Size.contains`.

File: lib/widgets/button.dart [hunk 25]
```diff
@@ -304,14 +307,53 @@ class _AnimatedScaleOnTapState extends State<AnimatedScaleOnTap> {
...
+          // `.buttons` are the pointer buttons which are pressed
+          // immediately after the action that caused the event.
+          // When the primary button is up, the button should be full-size.
+          _changeScale(1);
+          _wasOutside = false;
+        }
+      },
+      onPointerCancel: (_) {
+        // The pointer is out of the child widget's bounds;
+        // the child should be full-size even if the primary pointer is down.
```
Comment (gnprice) [inline lib/widgets/button.dart]: Given what we learned at https://github.com/zulip/zulip-flutter/pull/1954#issuecomment-3810208282 , it seems like this comment isn't accurate.

File: lib/widgets/button.dart [hunk 26]
```diff
@@ -304,14 +307,53 @@ class _AnimatedScaleOnTapState extends State<AnimatedScaleOnTap> {
...
+    if (box == null) return;
+
+    final Offset localPosition = box.globalToLocal(event.position);
+    final bool isOutside = localPosition.dx < 0 || localPosition.dy < 0 ||
+      localPosition.dy > box.size.height ||
+      localPosition.dx > box.size.width;
+
+    if (isOutside && !_wasOutside) {
+      _wasOutside = true;
+      _changeScale(1.0);
```
Comment (gnprice) [inline lib/widgets/button.dart:315]: Does this logic around `_wasOutside` have any effect? What if we remove that field entirely? The field is definitely making this widget's behavior more complex to reason about.

File: test/widgets/button_test.dart [hunk 27]
```diff
@@ -116,4 +117,70 @@ void main() {
...
+      await prepare(tester);
+
+      final gesture = await tester.startGesture(tester.getCenter(find.byType(ZulipIconButton)));
+      await tester.pump();
+      checkAnimatedScale(tester, 0.95);
+
+      final height = tester.getSize(find.byType(ZulipIconButton)).height;
+      await gesture.moveBy(Offset(0, -2*height));
+      await tester.pumpAndSettle();
+      checkAnimatedScale(tester, 1.0);
```
Comment (gnprice) [inline test/widgets/button_test.dart:183]: Avoid pumpAndSettle:
https://github.com/flutter/flutter/blob/0c2d316b1565bc97fcf6125fa87dfb90ef05ed8f/docs/contributing/Style-guide-for-Flutter-repo.md#avoid-using-pumpandsettle

Here in particular, it makes it unclear whether the test is checking what it intends to check: maybe the code's behavior is that the button scales down at first but then scales back up after a short time. That'd be a plausible design choice, even.

**Comment by MritunjayTiwari14** [comment]
Thank you @chrisbobbe for the review and suggestion. Particularly the `git grep` was a worth a thousand. I have pushed new changes which removed some redundant variables for the check. PTAL.

File: lib/widgets/button.dart [hunk 28]
```diff
@@ -304,13 +306,47 @@ class _AnimatedScaleOnTapState extends State<AnimatedScaleOnTap> {
...
   }
 
+  void _checkBounds(PointerEvent event) {
+    final box = context.findRenderObject() as RenderBox?;
+    if (box == null) return;
+
+    final localPosition = box.globalToLocal(event.position);
+    _isOutSide = !box.size.contains(localPosition);
+
+    if (_isOutSide) {
```
Comment (gnprice) [inline lib/widgets/button.dart]: Does storing this as a field on the object have any effect? It seems like it doesn't: the only place it's consulted is here, and we set it just above. So it could more simply be a local variable here and behave exactly the same.

Comment (gnprice) [reply lib/widgets/button.dart]: Separately, a nit: "outside" is one word, so `isOutside`.

File: lib/widgets/button.dart [hunk 29]
```diff
@@ -304,13 +306,47 @@ class _AnimatedScaleOnTapState extends State<AnimatedScaleOnTap> {
...
+      onPointerCancel: (_) {
+        // Return child to full-size on system-level interruption
+        // (e.g., notification, app backgrounding).
+        _changeScale(1);
+        _isOutSide = false;
+      },
+      onPointerMove: (event) {
+        // The pointer is out of the child widget's bounds;
+        // the child should be full-size even if the primary pointer is down.
+        _checkBounds(event);
```
Comment (gnprice) [inline lib/widgets/button.dart:342]: When you're adding (or moving) a comment, please take time to reread it to make sure it makes sense. This comment definitely isn't accurate here — we don't know the pointer is outside the bounds, which is why the thing we do next is check whether it is.

File: lib/widgets/button.dart (hunk 28 above)
Comment (MritunjayTiwari14) [reply lib/widgets/button.dart]: Since the variable value is consulted only once even inside the function. So it would be better pass the value directly to the condition rather than holding it inside a variable.

**Comment by MritunjayTiwari14** [comment]
Thank you @gnprice for the quick reply. I have pushed new changes. Please Take a Look!

**Comment by gnprice** [comment]
Thanks! This all looks good now; merging.

I've rewritten the commit message:

      ## Commit message ##
    -    button: Replace GestureDetector with Listener for `AnimatedScaleOnPress`
    +    button: Scale buttons immediately on press, without onTapDown delay
     
         Fixes #1953.

This way the commit message is clearer about what the purpose of the change is, and the desired effect as seen by the user. The internal details like Listener vs. GestureDetector are things that one can get easily by just reading the code in the diff.
