### PR TITLE
initial_snapshot: Centralize group-permission defaults; fix admin permission for legacy servers

### LINKED ISSUE #1850: Make `role:administrators` the default for `realm_can_delete_any_message_group`
Server 10 added the `realm_can_delete_any_message_group` permission. For servers before that, we're meant to use `role:administrators` when deciding whether to show the "delete message" button, but (with #1842, not yet merged) we'll actually use `role:nobody`. We should fix that and refactor a bit; see discussion: https://github.com/zulip/zulip-flutter/pull/1842#discussion_r2331362461

### PR DESCRIPTION
**Pull request by chrisbobbe**
Fixes #1850.

Also does the refactor Greg suggested here: https://github.com/zulip/zulip-flutter/pull/1842#discussion_r2331337006

### CODE REVIEW

File: lib/api/model/initial_snapshot.dart [hunk 1]
```diff
@@ -660,12 +666,115 @@ class SupportedPermissionSettings {
...
+}
+
+/// A known special string
+/// that [PermissionSettingsItem.defaultGroupName] might be.
+///
+/// See server implementation, e.g.
+/// `can_administer_channel_group` in zerver/models/streams.py.
+@JsonEnum(valueField: 'apiValue', alwaysCreate: true)
+enum PseudoSystemGroupName implements SettableAsDefaultGroupName {
+  streamCreatorOrNobody(apiValue: 'stream_creator_or_nobody'),
```
Comment (chrisbobbe) [inline lib/api/model/initial_snapshot.dart]: On CZO I proposed documenting this: [#api design > stream_creator_or_nobody @ 💬](https://chat.zulip.org/#narrow/channel/378-api-design/topic/stream_creator_or_nobody/near/2258637)

From that discussion, it looks like it might also get renamed.

File: lib/api/model/initial_snapshot.dart [hunk 2]
```diff
@@ -660,12 +666,115 @@ class SupportedPermissionSettings {
...
+  String toJson() => _$PseudoSystemGroupNameEnumMap[this]!;
+}
+
+/// A known canonical name for a system group.
+///
+/// Doc: https://zulip.com/api/group-setting-values#system-groups
+@JsonEnum(valueField: 'apiValue', alwaysCreate: true)
+enum SystemGroupName implements SettableAsDefaultGroupName {
+  everyoneOnInternet(apiValue: 'role:internet'),
+  everyone(apiValue: 'role:everyone'),
```
Comment (gnprice) [inline lib/api/model/initial_snapshot.dart]: This feels like it's not specifically about the initial snapshot — it'll eventually be relevant to other parts of the API too. It could go in `model.dart`… but perhaps better:

Let's have a prep commit move SupportedPermissionSettings and PermissionSettingsItem to their own file, say `permission.dart`. Then these new types can go there too.

File: lib/api/model/initial_snapshot.dart [hunk 3]
```diff
@@ -660,12 +666,115 @@ class SupportedPermissionSettings {
...
+/// - an unknown system group or special string [DefaultGroupNameUnknown]
+sealed class SettableAsDefaultGroupName {
+  String toJson();
+}
+
+class DefaultGroupNameConverter extends JsonConverter<SettableAsDefaultGroupName, String> {
+  const DefaultGroupNameConverter();
+
+  @override
+  SettableAsDefaultGroupName fromJson(String json) {
```
Comment (gnprice) [inline lib/api/model/initial_snapshot.dart]: Can this converter be merged into the class? Seems like any time we'd want this class, we'd want this same conversion, right?

(The `fromJson` method then becomes a factory constructor on that class. See other non-generated `fromJson` implementations, like on GroupSettingValue.)

File: lib/api/model/initial_snapshot.dart [hunk 4]
```diff
@@ -660,12 +666,115 @@ class SupportedPermissionSettings {
...
   Map<String, dynamic> toJson() => _$PermissionSettingsItemToJson(this);
 }
+
+/// A value of [PermissionSettingsItem.defaultGroupName].
+///
+/// Can be any of these:
+/// - a known system group [SystemGroupName]
+/// - a known special string [PseudoSystemGroupName]
+/// - an unknown system group or special string [DefaultGroupNameUnknown]
+sealed class SettableAsDefaultGroupName {
```
Comment (gnprice) [inline lib/api/model/initial_snapshot.dart]: Is there some information that the "settable as" part of the name is meant to convey here? How does the expressed meaning differ from if we called it `DefaultGroupName`?

File: lib/api/model/initial_snapshot.dart (hunk 1 above)
Comment (gnprice) [reply lib/api/model/initial_snapshot.dart]: Cool. Let's include a link to that thread in a comment, too.

File: lib/model/realm.dart [hunk 5]
```diff
@@ -236,11 +239,48 @@ class RealmStoreImpl extends HasUserGroupStore with RealmStore {
...
+    switch (config.defaultGroupName) {
+      case DefaultGroupNameUnknown():
+        // When we know about a permission, we should also know about the group
+        // we've said is the default value for it.
+        assert(false);
+        return true;
+      case PseudoSystemGroupName.streamCreatorOrNobody:
+        // TODO implement
+        return true;
+      case SystemGroupName.everyoneOnInternet:
```
Comment (gnprice) [inline lib/model/realm.dart]: nit: let's move all this logic to its own method, even if it's a private method located in this same place.

That way `selfHasPermissionForGroupSetting` gets to stay focused on the main logic it's about, rather than these details which are for a fallback case. As a bonus, this case can go into an early return, so that the method ends with the call to `selfInGroupSetting` which is the thrust of the method's main narrative.

File: lib/model/realm.dart [hunk 6]
```diff
@@ -236,11 +239,48 @@ class RealmStoreImpl extends HasUserGroupStore with RealmStore {
...
+
+    switch (config.defaultGroupName) {
+      case DefaultGroupNameUnknown():
+        // When we know about a permission, we should also know about the group
+        // we've said is the default value for it.
+        assert(false);
+        return true;
+      case PseudoSystemGroupName.streamCreatorOrNobody:
+        // TODO implement
+        return true;
```
Comment (gnprice) [inline lib/model/realm.dart]: Hmm — this is a concerning-looking type of TODO comment, because it feels like it's not something we'd necessarily see when the time comes that we need to carry it out.

Is there an issue for a feature where we'd expect to start hitting this case?

Oh also: these defaults come from our code and not the server, so it would take a change to our code for us to start hitting this. Let's add an assert — that should catch any such change while in dev, to remind us this isn't yet implemented.

File: lib/model/realm.dart [hunk 7]
```diff
@@ -236,11 +239,48 @@ class RealmStoreImpl extends HasUserGroupStore with RealmStore {
...
+      case SystemGroupName.everyoneOnInternet:
+      case SystemGroupName.everyone:
+        return true;
+      case SystemGroupName.members:
+        return _selfUserRole.isAtLeast(UserRole.member);
+      case SystemGroupName.fullMembers:
+        // TODO check waiting period (nontrivial to get access to that logic
+        //   here in RealmStore; it's on UserStore, which depends on RealmStore)
+        return _selfUserRole.isAtLeast(UserRole.member);
```
Comment (gnprice) [inline lib/model/realm.dart]: Hmm. That's the `hasPassedWaitingPeriod` method, right?

We can just move that to the RealmStore mixin instead of UserStore — it's not using anything from the user *store* itself, just a `User` object. Can include a comment justifying that placement by saying it's needed for permissions.

File: lib/model/realm.dart [hunk 8]
```diff
@@ -236,11 +239,48 @@ class RealmStoreImpl extends HasUserGroupStore with RealmStore {
...
+        // When we know about a permission, we should also know about the group
+        // we've said is the default value for it.
+        assert(false);
+        return true;
+      case PseudoSystemGroupName.streamCreatorOrNobody:
+        // TODO implement
+        return true;
+      case SystemGroupName.everyoneOnInternet:
+      case SystemGroupName.everyone:
+        return true;
```
Comment (gnprice) [inline lib/model/realm.dart:305]: Do we have an issue for spectator view? If not, probably good to file one for tracking. (Can be terse and dashed off — it'll be MXB.) Then the `everyoneOnInternet` line here can get a TODO line pointing to that… or perhaps better, have such a comment at the definition of that enum value, saying to audit all its references.

File: test/model/realm_test.dart [hunk 9]
```diff
@@ -82,6 +84,94 @@ void main() {
...
+
+      for (final systemGroupName in SystemGroupName.values) {
+        switch (systemGroupName) {
+          case SystemGroupName.everyoneOnInternet:
+            // (No permissions where we use this default value; continue.)
+            break;
+          case SystemGroupName.everyone:
+            test('everyone', () {
+              prepare();
+              doCheck(GroupSettingType.realm, 'can_access_all_users_group', true);
```
Comment (gnprice) [inline test/model/realm_test.dart]: nit: strengthen the test
```suggestion
          case SystemGroupName.everyone:
            test('everyone', () {
              prepare(selfUserRole: UserRole.guest);
              doCheck(GroupSettingType.realm, 'can_access_all_users_group', true);
```

and similarly `.owner` for the `.nobody` case at the end

**Review by gnprice — COMMENTED** [review]
Thanks for building this! Comments below.

File: lib/api/model/initial_snapshot.dart (hunk 4 above)
Comment (chrisbobbe) [reply lib/api/model/initial_snapshot.dart]: Ah nope 🙂 I think I'd had the idea that it should be considered an interface rather than a base class, but I don't really remember why, and I don't see anything wrong with `DefaultGroupName` when I look at it again :)

File: lib/model/realm.dart (hunk 6 above)
Comment (chrisbobbe) [reply lib/model/realm.dart]: Good points, yep—

> Is there an issue for a feature where we'd expect to start hitting this case?

—#1102

File: lib/model/realm.dart (hunk 7 above)
Comment (chrisbobbe) [reply lib/model/realm.dart]: Sure, I can do that. `RealmStore` doesn't have access to the self-user `User` object, and it would feel odd to ask `selfHasPermissionForGroupSetting`'s callers to provide it. But the passed-waiting-period method just uses `.dateJoined` from the user, and we can store that in `RealmStoreImpl` as `._selfUserDateJoined`, the way we already have `._selfUserRole` there, if that makes sense.

Comment (gnprice) [reply lib/model/realm.dart]: Hmm true. But yeah, that solution works. The implementation will then live on RealmStoreImpl rather than on the mixin, which is fine.

**Comment by chrisbobbe** [comment]
Thanks for the review! Revision pushed.

File: lib/widgets/action_sheet.dart [hunk 10]
```diff
@@ -436,6 +436,8 @@ void showChannelActionSheet(BuildContext context, {
   required int channelId,
   bool showTopicListButton = true,
 }) {
+  final now = DateTime.now();
```
Comment (chrisbobbe) [inline lib/widgets/action_sheet.dart]: Ah I think I should change this to `ZulipBinding.instance.utcNow()`; will do that in my next revision.

File: lib/widgets/all_channels.dart [hunk 11]
```diff
@@ -93,7 +93,7 @@ class AllChannelsListEntry extends StatelessWidget {
     final designVariables = DesignVariables.of(context);
     final channel = this.channel;
     final Subscription? subscription = channel is Subscription ? channel : null;
-    final hasContentAccess = store.selfHasContentAccess(channel);
+    final hasContentAccess = store.selfHasContentAccess(channel, atDate: DateTime.now());
```
Comment (gnprice) [inline lib/widgets/all_channels.dart]: There aren't currently any defaults with the
    "role:fullmembers" value, so this won't control any behavior now.
    But some might be added in the future, and we might as well include
    it for completeness.

Hmm — there probably won't ever be any of these, though. So it's unfortunate to be making this API more awkward for the code across the app to use, when the extra complication only gets used (a) in a fallback for old servers (b) and only after a hypothetical future change we don't expect to happen.

File: lib/model/realm.dart [hunk 12]
```diff
@@ -236,13 +272,61 @@ class RealmStoreImpl extends HasUserGroupStore with RealmStore {
...
+      case SystemGroupName.members:
+        return _selfUserRole.isAtLeast(UserRole.member);
+      case SystemGroupName.fullMembers:
+        if (!_selfUserRole.isAtLeast(UserRole.member)) return false;
+        if (_selfUserRole == UserRole.member) {
+          return selfHasPassedWaitingPeriod(byDate: atDate);
+        }
+        return true;
```
Comment (gnprice) [inline lib/model/realm.dart]: How about we instead just make this unimplemented, like `.streamCreatorOrNobody` above?

The difference being that in this case, we don't expect to ever add code that triggers this case. (I think we may have never had a permission that defaulted to "full members". If we ever add one in the future, we'd probably make the permission configurable and group-based from the beginning, so there would still never be a fallback to such a default for it.)

File: lib/model/realm.dart [hunk 13]
```diff
@@ -128,9 +129,24 @@ mixin RealmStore on PerAccountStoreBase, UserGroupStore {
...
+  /// to be a full member.
+  ///
+  /// See:
+  ///   https://zulip.com/api/roles-and-permissions#determining-if-a-user-is-a-full-member
+  ///
+  /// To determine if the self-user is a full member,
+  /// callers must also check that the user's role is at least [UserRole.member].
+  // This used to be a method on [UserStore], but we needed it for permissions
+  // here in [RealmStore].
+  bool selfHasPassedWaitingPeriod({required DateTime byDate});
```
Comment (gnprice) [inline lib/model/realm.dart:140]: I think the refactor to move this here is still fine, though — logically its purpose is about permissions (that's the only reason to care about having passed the waiting period), so it makes sense for it to live where the permission checks are.

**Comment by chrisbobbe** [comment]
Thanks for the review! Revision pushed.

**Comment by gnprice** [comment]
Thanks! Looks good; merging.
