### PR TITLE
content: Fix bugs where `TextSpan` styles clobber each other with `InlineContent.style` attributes

### LINKED ISSUE #806: content: Inline code links should be rendered with the link color
We should fix inline code's color when it is a part of a link.

| web (expected) | flutter |
| - | - |
| Screenshot from 2024-07-11 21-33-29 |   |

Since a recent change (https://github.com/zulip/zulip-flutter/commit/299c76be7), inline code links no longer have the ambient color and is always black. We want to fix this to match the behavior of the web app.

For reference, the web app [defines](https://github.com/zulip/zulip/blob/4d34a902c9c2c7df87ded0ce5a05df7ccf052c97/web/styles/app_variables.css#L494-L495) a separate CSS variable `--color-markdown-code-link`

```css
    --color-markdown-link: hsl(200deg 100% 40%);
    --color-markdown-code-link: var(--color-markdown-link);
```

that [applies to](https://github.com/zulip/zulip/blob/4d34a902c9c2c7df87ded0ce5a05df7ccf052c97/web/styles/rendered_markdown.css#L679C1-L685) inline code that appears inside a link:

```
    & a {
        color: var(--color-markdown-link);
        text-decoration: none;

        & code {
            color: var(--color-markdown-code-link);
        }
```

### LINKED ISSUE #1812: content: Inline code in a bold span should be bold (but isn't)
### References
* Related symptom: #1813 
* Related symptom: #806

### LINKED ISSUE #1817: content: Bold text in strikethrough should have strikethrough line, but doesn't

### LINKED ISSUE #1818: content: Unicode emoji in strikethrough should have strikethrough line, but doesn't

### PR DESCRIPTION
**Pull request by chrisbobbe**
Fixes #806.
Fixes #1812.
Fixes #1817.
Fixes #1818.

There are other issues with inline-span styles:
- #1813
- #1819
- (possibly more)

but I think those all involve `WidgetSpan`s in `InlineContent`'s span tree and can be addressed separately.

| Before | After |
| --- | --- |
| image | image |
| image | image |

### CODE REVIEW

File: test/widgets/content_test.dart [hunk 1]
```diff
@@ -719,6 +729,22 @@ void main() {
         targetHtml: '<code>code</code>',
         targetFontSizeFinder: mkTargetFontSizeFinderFromPattern('code'));
     });
+
+    testFontWeight('is bold in bold span',
+      // Regression test for: https://github.com/zulip/zulip-flutter/issues/1812
+      expectedWght: 600,
+      // **bold**
+      content: plainContent('<p><strong><code>bold</code></strong></p>'),
```
Comment (gnprice) [inline test/widgets/content_test.dart]:
```suggestion
    testFontWeight('is bold in bold span',
      // Regression test for: https://github.com/zulip/zulip-flutter/issues/1812
      expectedWght: 600,
      // **`bold`**
      content: plainContent('<p><strong><code>bold</code></strong></p>'),
```

right?

File: test/widgets/content_test.dart [hunk 2]
```diff
@@ -1028,9 +1062,39 @@ void main() {
...
+        // Regression test for: https://github.com/zulip/zulip-flutter/issues/1812
+        expectedWght: 600,
+        // **bold**
+        content: plainContent('<p><strong><span class="katex">'
+          '<span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>λ</mi></mrow>'
+            '<annotation encoding="application/x-tex"> \\lambda </annotation></semantics></math></span>'
+          '<span class="katex-html" aria-hidden="true">'
+            '<span class="base unknown">' // Server doesn't generate this 'unknown' class.
+            '<span class="strut" style="height:0.6944em;"></span>'
+            '<span class="mord mathnormal">λ</span></span></span></span></strong></p>'),
```
Comment (gnprice) [inline test/widgets/content_test.dart]: How about something like:

```suggestion
        content: plainContent('<p><strong>$unsupportedKatexHtml</strong></p>'),
```

where that string is shared between these two new tests and the existing one above? That way it's clear that the bulk of the logic is in common, and one can more easily focus on the bits that differ.

**Review by gnprice — COMMENTED** [review]
Thanks for fixing these! Generally all looks good; a couple of nits.

File: test/widgets/content_test.dart (hunk 2 above)
Comment (chrisbobbe) [reply test/widgets/content_test.dart]: Makes sense; see what you think in my next revision

**Comment by chrisbobbe** [comment]
Thanks for the reviews! Revision pushed.

File: test/widgets/content_test.dart [hunk 3]
```diff
@@ -1047,8 +1047,7 @@ void main() {
     });
 
     testWidgets('fallback to displaying KaTeX source if unsupported KaTeX HTML', (tester) async {
-      await prepareContent(tester, plainContent(ContentExample.mathInlineUnknown.html));
-      tester.widget(find.text(r'\lambda'));
+      testContentSmoke(ContentExample.mathInlineUnknown);
```
Comment (gnprice) [inline test/widgets/content_test.dart]: This is a test nested in a test, right? So the outer should become a group instead. (Like it does in the next commit anyway.)

File: test/widgets/content_test.dart [hunk 4]
```diff
@@ -1028,9 +1062,29 @@ void main() {
...
-    testWidgets('fallback to displaying KaTeX source if unsupported KaTeX HTML', (tester) async {
-      await prepareContent(tester, plainContent(ContentExample.mathInlineUnknown.html));
-      tester.widget(find.text(r'\lambda'));
+    group('fallback to displaying KaTeX source if unsupported KaTeX HTML', () {
+      testContentSmoke(ContentExample.mathInlineUnknown);
+
+      assert(ContentExample.mathInlineUnknown.html.startsWith('<p>'));
+      assert(ContentExample.mathInlineUnknown.html.endsWith('</p>'));
+      final unsupportedKatexHtml = ContentExample.mathInlineUnknown.html
+        .substring(3, ContentExample.mathInlineUnknown.html.length - 4);
```
Comment (gnprice) [inline test/widgets/content_test.dart]: Hmm, I see.

Can this also apply to the test above that has similar HTML?
```dart
    testWidgets('maintains font-size ratio with surrounding text, when falling back to TeX source', (tester) async {
      const unsupportedHtml = '<span class="katex">'
        '<span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>λ</mi></mrow>'
          '<annotation encoding="application/x-tex"> \\lambda </annotation></semantics></math></span>'
        '<span class="katex-html" aria-hidden="true">'
          '<span class="base unknown">' // Server doesn't generate this 'unknown' class.
          '<span class="strut" style="height:0.6944em;"></span>'
          '<span class="mord mathnormal">λ</span></span></span></span>';
      await checkFontSizeRatio(tester,
        targetHtml: unsupportedHtml,
        targetFontSizeFinder: mkTargetFontSizeFinderFromPattern(r'\lambda'));
    });
```

That's the one I had in mind at https://github.com/zulip/zulip-flutter/pull/1820#discussion_r2289397500 :slightly_smiling_face: — I guess that was ambiguous.

File: test/widgets/content_test.dart [hunk 5]
```diff
@@ -1028,9 +1062,29 @@ void main() {
...
+
+      testFontWeight('is bold in bold span',
+        // Regression test for: https://github.com/zulip/zulip-flutter/issues/1812
+        expectedWght: 600,
+        // **$$ \lambda $$**
+        content: plainContent('<p><strong>$unsupportedKatexHtml</strong></p>'),
```
Comment (gnprice) [inline test/widgets/content_test.dart]: nit:
```suggestion
        content: plainContent('<p><strong>$unsupportedKatexHtml</strong></p>'),
```

This isn't HTML that we'd expect the server to emit for that input (or any input).

File: test/widgets/content_test.dart [hunk 6]
```diff
@@ -1028,9 +1062,29 @@ void main() {
...
+        styleFinder: (tester) => mergedStyleOf(tester, r'\lambda')!,
```
Comment (gnprice) [inline test/widgets/content_test.dart]: nit: can avoid the need to look up the example to see that `\lambda` is the right text to look for:
```suggestion
        styleFinder: (tester) => mergedStyleOf(tester, ContentExample.mathInlineUnknown.expectedText)!,
```

(or maybe pull that into a variable next to `unsupportedKatexHtml`)

**Review by gnprice — COMMENTED** [review]
Thanks! Comments below.

**Comment by chrisbobbe** [comment]
Thanks! Revision pushed.

File: test/widgets/content_test.dart [hunk 7]
```diff
@@ -1010,27 +1044,35 @@ void main() {
...
-          '<span class="strut" style="height:0.6944em;"></span>'
-          '<span class="mord mathnormal">λ</span></span></span></span>';
-      await checkFontSizeRatio(tester,
-        targetHtml: unsupportedHtml,
-        targetFontSizeFinder: mkTargetFontSizeFinderFromPattern(r'\lambda'));
-    });
+    group('fallback to displaying KaTeX source if unsupported KaTeX HTML', () {
+      testContentSmoke(ContentExample.mathInlineUnknown);
 
-    testWidgets('displays KaTeX content', (tester) async {
```
Comment (gnprice) [inline test/widgets/content_test.dart:1026]: nit:

    Looks like the behavior of that test differs from this one, just in
    not passing `findRichText: true`. But that didn't stop it from
    finding the expected test and passing, so, shrug.

s/expected test/expected text/ ?

File: test/widgets/content_test.dart [hunk 8]
```diff
@@ -1010,27 +1044,35 @@ void main() {
...
-      const unsupportedHtml = '<span class="katex">'
-        '<span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>λ</mi></mrow>'
-          '<annotation encoding="application/x-tex"> \\lambda </annotation></semantics></math></span>'
-        '<span class="katex-html" aria-hidden="true">'
-          '<span class="base unknown">' // Server doesn't generate this 'unknown' class.
-          '<span class="strut" style="height:0.6944em;"></span>'
-          '<span class="mord mathnormal">λ</span></span></span></span>';
-      await checkFontSizeRatio(tester,
-        targetHtml: unsupportedHtml,
-        targetFontSizeFinder: mkTargetFontSizeFinderFromPattern(r'\lambda'));
```
Comment (gnprice) [inline test/widgets/content_test.dart:1023]: nit: squash these together:

9cc505f03 content test [nfc]: Get unsupported-katex HTML from ContentExample
bf823e119 content test [nfc]: Pull out an `expectedText` variable from ContentExample

since the first one leaves the literal `r'\lambda'` unexplained

**Review by gnprice — COMMENTED** [review]
Thanks for cleaning up these tests! Just a couple of nits.

**Comment by chrisbobbe** [comment]
Thanks! Revision pushed.

**Comment by gnprice** [comment]
Thanks! Looks good; all clear to merge, pending CI.

**Comment by chrisbobbe** [comment]
Thanks! Done.
