### PR TITLE
avatar: Show placeholder on image load error

### LINKED ISSUE #1558: For avatars that don't load, reuse muted-user placeholder?
For #296, we'll add a simple "person"-icon placeholder for an avatar image, to use when the user is muted.

Perhaps we could reuse this for when the real avatar doesn't load, either because the URL is invalid or, with `RealmContentNetworkImage.errorBuilder`, because its request fails (an instance of #265). Or, pre-#1556, for a message from an unknown sender (but we should eventually do #1556 for that).

This won't be ripe to work on until #296 is resolved. Please don't try to claim this issue if #296 is still open.

### PR DESCRIPTION
**Pull request by vinodsingh-dev-gsoc**
Fixes #1558.
This change improves the user experience by displaying a consistent placeholder when an avatar image fails to load from its URL.
Adds an `errorBuilder` to the `AvatarImage` widget and includes a test case to verify the new behavior.
Co-authored-by: Chris Bobbe [cbobbe@zulip.com](mailto:cbobbe@zulip.com)

### CODE REVIEW

**Comment by chrisbobbe** [comment]
Thanks for the PR! Please post before/after screenshots of the change. Please also change the commit sequence so the tests are added in the same commit that adds the behavior being tested.

**Comment by vinodsingh-dev-gsoc** [comment]
Hi  chrisbobbe! Thanks a lot for the detailed feedback. I'm currently working on your suggestions. I've gathered the before/after screenshots and am now in the process of squashing the commits and fixing the test suite to make the PR perfect. I'll push the updated changes shortly! 😊

**Comment by vinodsingh-dev-gsoc** [comment]
| status| CombinedScreen | DM List | Profile Screen |
|--------|--------|--------|--------|
|Before| before_fix_for_combined_list| before_fix_for_dm_list|before_fix_for_profile_page|
| After fix | after_fix_for_combined_list | after_fix_for_dm_list|after_fix_profile_page|

--------
As you can see in the "After" screenshot, the fix ensures that a placeholder is now displayed whenever an avatar URL is null or fails to load, instead of showing a blank space. This provides a clearer and more consistent UI for the user.

File: test/widgets/user_test.dart [hunk 1]
```diff
@@ -1,18 +1,26 @@
...
 import '../stdlib_checks.dart';
 import '../test_images.dart';
+import 'test_app.dart';
+
+class MockHttpClient extends Fake implements HttpClient {
+  @override
+  Future<HttpClientRequest> getUrl(Uri url) async {
+    throw const SocketException('test error');
+  }
+}
```
Comment (chrisbobbe) [inline test/widgets/user_test.dart]: This looks like the kind of thing that `FakeImageHttpClient` is for, in test/test_images.dart. Can we use that?

Oh! Or maybe add a boolean `success` param to `prepareBoringImageHttpClient` in that file (defaulting to `true`), and pass `false` in this case to make it prepare an `HttpStats.notFound` response?

File: test/widgets/user_test.dart [hunk 2]
```diff
@@ -78,5 +86,28 @@ void main() {
...
+          TestZulipApp(
+            accountId: eg.selfAccount.id,
+            child: AvatarImage(userId: user.userId, size: 32),
+          ),
+        );
+        await tester.pump(); // Image provider is created
+        await tester.pump(); // Image fails to load
+        expect(find.byIcon(ZulipIcons.person), findsOneWidget);
+
+        expect(find.byType(DecoratedBox), findsOneWidget);
```
Comment (chrisbobbe) [inline test/widgets/user_test.dart]: This seems like it could easily find a `DecoratedBox` that's not related to the behavior we're testing.

Comment (chrisbobbe) [reply test/widgets/user_test.dart]: How about checking the icon in this way:

```dart
        check(find.descendant(
          of: find.byType(AvatarImage),
          matching: find.byIcon(ZulipIcons.person),
        )).findsOne();
```

(adding the `import 'package:flutter_checks/flutter_checks.dart';` at the top as needed)

File: test/widgets/user_test.dart [hunk 3]
```diff
@@ -78,5 +86,28 @@ void main() {
...
+        final store = await testBinding.globalStore.perAccount(eg.selfAccount.id);
+        final user = eg.user(avatarUrl: 'https://zulip.com/avatar.png');
+        await store.addUser(user);
+
+        await tester.pumpWidget(
+          TestZulipApp(
+            accountId: eg.selfAccount.id,
+            child: AvatarImage(userId: user.userId, size: 32),
+          ),
+        );
```
Comment (chrisbobbe) [inline test/widgets/user_test.dart]: nit: make more compact:

```suggestion
        await tester.pumpWidget(TestZulipApp(
          accountId: eg.selfAccount.id,
          child: AvatarImage(userId: user.userId, size: 32)));
```

File: lib/widgets/user.dart [hunk 4]
```diff
@@ -90,6 +89,9 @@ class AvatarImage extends StatelessWidget {
       avatarUrl.get(physicalSize),
       filterQuality: FilterQuality.medium,
       fit: BoxFit.cover,
+      errorBuilder: (context, error, stackTrace) {
+        return _AvatarPlaceholder(size: size);
+      },
```
Comment (chrisbobbe) [inline lib/widgets/user.dart]: nit: make more compact:

```suggestion
      errorBuilder: (_, _, _) => _AvatarPlaceholder(size: size),
```

**Review by chrisbobbe — COMMENTED** [review]
Thanks! Small comments below.

**Comment by chrisbobbe** [comment]
Also please update the commit message to mention the issue being fixed, according to our style.

**Comment by chrisbobbe** [comment]
I see you've pushed some changes, but I'm not sure if you intend them to be ready for review; I assume you'll comment here when ready. 🙂

**Comment by vinodsingh-dev-gsoc** [comment]
Hi @chrisbobbe,

Thanks for the ping, and my apologies for the delay in updating you here.

I've addressed your suggestions and pushed the commits a few days ago. The PR should now be ready for another look.

Eager to hear your feedback. Thank you for your guidance!

**Comment by alya** [comment]
Please see our guide on how to demonstrate visual changes: https://zulip.readthedocs.io/en/latest/contributing/reviewable-prs.html#demonstrating-visual-changes. The before/after screenshots should be minimally different.

I would also like to see both placeholders and regular avatars in the same screenshot, and dark theme as well as light.

**Comment by vinodsingh-dev-gsoc** [comment]
> Please see our guide on how to demonstrate visual changes: https://zulip.readthedocs.io/en/latest/contributing/reviewable-prs.html#demonstrating-visual-changes. The before/after screenshots should be minimally different.
> 
> I would also like to see both placeholders and regular avatars in the same screenshot, and dark theme as well as light.



Hi @alya, thanks for the detailed feedback! That makes perfect sense. I will generate the new screenshots with both themes and mixed avatars as you suggested and will post them here shortly.

**Comment by vinodsingh-dev-gsoc** [comment]
| Before (Bot avatar URL fails)| After Fix (Shows Placeholder) |
|--------|--------|
| before_fix_for_combined_list_bot_logo_not_loaded_light_mode| after_fix_for_combined_list_bot_logo_not_loaded |
| before_fix_for_combined_list_bot_logo_not_loaded_dark_mode| after_fix_for_combined_list_bot_logo_not_loaded_DarkMode|

**Comment by vinodsingh-dev-gsoc** [comment]
Hi @alya and @chrisbobbe,

Thanks for the detailed feedback! I've now updated the PR description with the new screenshots to better demonstrate the visual changes.

As requested, I've included before/after images for both light and dark themes, which show both regular avatars and the new placeholders in the same view.

I believe this addresses all the points. Eager for your review when you have a moment. Thank you!

**Comment by gnprice** [comment]
Thanks. Please see our guidelines on a clean Git history (linked from this repo's README):
https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html

and revise these commits to follow those guidelines.

File: lib/widgets/user.dart [hunk 5]
```diff
@@ -1,5 +1,4 @@
 import 'package:flutter/material.dart';
-
```
Comment (chrisbobbe) [inline lib/widgets/user.dart:2]: Please don't delete this blank line; it separates third-party imports from our own imports. (Here and elsewhere in the PR.)

File: lib/widgets/user.dart [hunk 6]
```diff
@@ -90,6 +89,7 @@ class AvatarImage extends StatelessWidget {
       avatarUrl.get(physicalSize),
       filterQuality: FilterQuality.medium,
       fit: BoxFit.cover,
+      errorBuilder: (_, _, _) => _AvatarPlaceholder(size: size),
```
Comment (chrisbobbe) [inline lib/widgets/user.dart:92]: Please also change the `resolvedUrl == null` case to return `_AvatarPlaceholder`, too, for this part of the issue description in #1558:

> because the URL is invalid

Comment (chrisbobbe) [reply lib/widgets/user.dart:92]: and add a test for that.

File: test/test_images.dart [hunk 7]
```diff
@@ -12,15 +12,20 @@ import 'package:flutter_test/flutter_test.dart';
...
+      ..statusCode = HttpStatus.ok
+      ..content = kSolidBlueAvatar;
+  } else {
+    httpClient.request.response
+      ..statusCode = HttpStatus.notFound
+      ..content = Uint8List(0);
+  }
   return httpClient;
 }
-
```
Comment (chrisbobbe) [inline test/test_images.dart:23]: Keep this blank line, which exists to give the code some breathing room so it's more readable.

File: test/widgets/user_test.dart [hunk 8]
```diff
@@ -78,5 +79,26 @@ void main() {
...
+      addTearDown(testBinding.reset);
+      prepareBoringImageHttpClient(success: false);
+      await testBinding.globalStore.add(eg.selfAccount, eg.initialSnapshot());
+      final store = await testBinding.globalStore.perAccount(eg.selfAccount.id);
+      final badUser = eg.user(avatarUrl: 'https://zulip.com/avatarinvalid.png');
+      await store.addUser(badUser);
+      await tester.pumpWidget(TestZulipApp(
+        child: PerAccountStoreWidget(
+          accountId: eg.selfAccount.id,
+          child: AvatarImage(userId: badUser.userId, size: 30))));
```
Comment (chrisbobbe) [inline test/widgets/user_test.dart]: Should be able to pass an `accountId` to `TestZulipApp` instead of adding a `PerAccountStoreWidget` here.

File: test/widgets/user_test.dart [hunk 9]
```diff
@@ -78,5 +79,26 @@ void main() {
...
+      await tester.pumpAndSettle();
+      expect(
+        find.descendant(
+          of: find.byType(AvatarImage),
+          matching: find.byIcon(ZulipIcons.person),
+        ),
+        findsOneWidget,
+      );
+  debugNetworkImageHttpClientProvider = null;
+    });
```
Comment (chrisbobbe) [inline test/widgets/user_test.dart]: nits:

- Empty line before a test
- Try to adjust indentation and spacing to follow the pattern of existing tests
- Use `check` instead of `expect`; see existing tests for examples

**Review by chrisbobbe — COMMENTED** [review]
Thanks! Comments below, and please also address Greg's feedback about the commit sequence.

File: lib/widgets/user.dart (hunk 6 above)
Comment (chrisbobbe) [reply lib/widgets/user.dart:92]: Same for the `user == null` case above that, for this part of the issue description:

> Or, pre-https://github.com/zulip/zulip-flutter/issues/1556, for a message from an unknown sender

**Comment by chrisbobbe** [comment]
I see you've pushed changes; please comment here when this is ready for another review (but please run `tools/check` locally and fix those issues first; I see CI is failing).

**Comment by vinodsingh-dev-gsoc** [comment]
Hi @chrisbobbe, thanks for the feedback!

I've fixed the test failures (related to new_dm_sheet_test.dart) and also resolved the merge conflicts .
I've run tools/check locally, and all tests are passing now. This should be ready for another review. Thanks!

File: lib/widgets/user.dart [hunk 10]
```diff
@@ -66,9 +66,8 @@ class AvatarImage extends StatelessWidget {
     final user = store.getUser(userId);
 
     if (user == null) { // TODO(log)
-      return const SizedBox.shrink();
+      return _AvatarPlaceholder(size: size);
     }
-
```
Comment (chrisbobbe) [inline lib/widgets/user.dart:71]: nit: keep this blank line, separating unrelated stanzas of code

File: test/widgets/user_test.dart [hunk 11]
```diff
@@ -1,18 +1,18 @@
...
 import 'package:flutter/material.dart';
-import 'package:flutter/rendering.dart';
 import 'package:flutter_test/flutter_test.dart';
 import 'package:zulip/model/store.dart';
 import 'package:zulip/widgets/image.dart';
+import 'package:zulip/widgets/icons.dart';
 import 'package:zulip/widgets/store.dart';
+import 'package:zulip/widgets/theme.dart';
 import 'package:zulip/widgets/user.dart';
-
```
Comment (chrisbobbe) [inline test/widgets/user_test.dart:10]: nit: keep this blank line, which separates third-party imports from first-party imports

File: test/widgets/new_dm_sheet_test.dart [hunk 12]
```diff
@@ -254,17 +254,31 @@ void main() {
...
-        check(icon).icon.equals(ZulipIcons.check_circle_checked);
+        check(find.descendant(
+          of: userTileFinder,
+          matching: find.byIcon(ZulipIcons.check_circle_checked),
+        )).findsOne();
+        check(find.descendant(
+          of: userTileFinder,
+          matching: find.byIcon(ZulipIcons.check_circle_unchecked),
+        )).findsNothing();
+
```
Comment (chrisbobbe) [inline test/widgets/new_dm_sheet_test.dart]: This can be shortened by making a helper:

```dart
        check(findInUserTile(user,
          find.byIcon(ZulipIcons.check_circle_checked))).findsOne();
        check(findInUserTile(user,
          find.byIcon(ZulipIcons.check_circle_unchecked))).findsNothing();
```

with `findInUserTile` defined as something like this, maybe just after where `findUserTile` is defined:

```dart
  Finder findInUserTile(User user, Finder finder) => 
    find.descendant(of: findUserTile(user), matching: finder);
```

and similarly in the `else` case.

Comment (chrisbobbe) [reply test/widgets/new_dm_sheet_test.dart]: Also, let's put this in a separate prep commit; by tightening these tests' expectations, we're making a helpful independent improvement.

File: test/widgets/user_test.dart [hunk 13]
```diff
@@ -28,9 +28,17 @@ void main() {
...
-      await tester.pumpWidget(GlobalStoreWidget(
-        child: PerAccountStoreWidget(accountId: eg.selfAccount.id,
-          child: AvatarImage(userId: user.userId, size: size ?? 30))));
+      await tester.pumpWidget(
+        MaterialApp(
+          theme: ThemeData(extensions: [
+            DesignVariables.light,
+          ]),
+          home: GlobalStoreWidget(
+            child: PerAccountStoreWidget(accountId: eg.selfAccount.id,
```
Comment (chrisbobbe) [inline test/widgets/user_test.dart]: This is what `TestZulipApp` is for—we shouldn't need to spell out all these details. (Here and in the other added tests.)

**Comment by vinodsingh-dev-gsoc** [comment]
Hi @chrisbobbe! I've pushed new updates addressing your feedback, especially regarding the refactor into a separate commit and using TestZulipApp for the test setup.

Could you please take another look when you have a moment? Thanks!

**Comment by vinodsingh-dev-gsoc** [comment]
Hello @chrisbobbe  I've pushed the new updates addressing your feedbacks .
Could you please take another look when you have a moment? Thanks!

File: test/widgets/user_test.dart [hunk 14]
```diff
@@ -28,9 +27,12 @@ void main() {
...
       prepareBoringImageHttpClient();
-      await tester.pumpWidget(GlobalStoreWidget(
-        child: PerAccountStoreWidget(accountId: eg.selfAccount.id,
-          child: AvatarImage(userId: user.userId, size: size ?? 30))));
+      await tester.pumpWidget(
+          TestZulipApp(
+            accountId: eg.selfAccount.id,
+            child: AvatarImage(userId: user.userId, size: size ?? 30),
+          )
+      );
```
Comment (chrisbobbe) [inline test/widgets/user_test.dart]: nit: keep indentation style (here and many other places):

```suggestion
      await tester.pumpWidget(
        TestZulipApp(accountId: eg.selfAccount.id,
          child: AvatarImage(userId: user.userId, size: size ?? 30)));
```

File: test/widgets/user_test.dart [hunk 15]
```diff
@@ -78,5 +80,72 @@ void main() {
...
+         TestZulipApp(
+          accountId: eg.selfAccount.id,
+          child: AvatarImage(userId: badUser.userId, size: 30)));
+      await tester.pumpAndSettle();
+      check(
+        find.descendant(
+          of: find.byType(AvatarImage),
+          matching: find.byIcon(ZulipIcons.person),
+        ).evaluate().length
+      ).equals(1);
```
Comment (chrisbobbe) [inline test/widgets/user_test.dart]: How about:

```suggestion
      check(find.descendant(
        of: find.byType(AvatarImage),
        matching: find.byIcon(ZulipIcons.person),
      )).findsOne();
```

or

```suggestion
      check(findPlaceholder).findsOne();
```

if you define `findPlaceholder` as a reusable helper.

(Here and everywhere this comment applies.)

**Review by chrisbobbe — COMMENTED** [review]
Thanks! Comments below.

Also some commit-message nits:

- In the first commit, `refactor(test):` doesn't follow our style for the prefix of the commit-message summary line. It should refer to a subsystem; see the doc: https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html#commit-summary-part-1
  - In this case I would choose `new-dm test:` or similar.
- In the second commit, check the style of the "Fixes" line: it should say `Fixes #1558.`

**Comment by vinodsingh-dev-gsoc** [comment]
Hi @chrisbobbe!

I've just pushed the final updates, addressing all the nits and feedback (indentation, test helpers, and commit messages).

This should be ready for a final review. Thanks for all your guidance! 🙏

File: test/widgets/new_dm_sheet_test.dart [hunk 16]
```diff
@@ -254,19 +254,19 @@ void main() {
...
+        if (expected) {
+          check(findUserChip(user)).findsOne();
+          check(findInUserTile(user,find.byIcon(ZulipIcons.check_circle_checked))).findsOne();
+          check(findInUserTile(user,find.byIcon(ZulipIcons.check_circle_unchecked))).findsNothing();
+        } else {
+          check(findUserChip(user)).findsNothing();
+          check(findInUserTile(user,find.byIcon(ZulipIcons.check_circle_unchecked))).findsOne();
+          check(findInUserTile(user,find.byIcon(ZulipIcons.check_circle_checked))).findsNothing();
+        }
       }
```
Comment (chrisbobbe) [inline test/widgets/new_dm_sheet_test.dart]:
```suggestion
    Finder findInUserTile(User user, Finder finder) => find.descendant(of: findUserTile(user), matching: finder);

    void checkUserSelected(WidgetTester tester, User user, bool expected) {
      if (expected) {
        check(findUserChip(user)).findsOne();
        check(findInUserTile(user,find.byIcon(ZulipIcons.check_circle_checked))).findsOne();
        check(findInUserTile(user,find.byIcon(ZulipIcons.check_circle_unchecked))).findsNothing();
      } else {
        check(findUserChip(user)).findsNothing();
        check(findInUserTile(user,find.byIcon(ZulipIcons.check_circle_unchecked))).findsOne();
        check(findInUserTile(user,find.byIcon(ZulipIcons.check_circle_checked))).findsNothing();
      }
    }
```

File: test/widgets/user_test.dart [hunk 17]
```diff
@@ -28,9 +33,9 @@ void main() {
       await store.addUser(user);
 
       prepareBoringImageHttpClient();
-      await tester.pumpWidget(GlobalStoreWidget(
-        child: PerAccountStoreWidget(accountId: eg.selfAccount.id,
-          child: AvatarImage(userId: user.userId, size: size ?? 30))));
+      await tester.pumpWidget(
+          TestZulipApp(accountId: eg.selfAccount.id,
+            child: AvatarImage(userId: user.userId, size: size ?? 30)));
```
Comment (chrisbobbe) [inline test/widgets/user_test.dart]:
```suggestion
      await tester.pumpWidget(
        TestZulipApp(accountId: eg.selfAccount.id,
          child: AvatarImage(userId: user.userId, size: size ?? 30)));
```

File: test/widgets/user_test.dart [hunk 18]
```diff
@@ -78,5 +83,48 @@ void main() {
...
+      final store = await testBinding.globalStore.perAccount(eg.selfAccount.id);
+      final badUser = eg.user(avatarUrl: 'https://zulip.com/avatarinvalid.png');
+      await store.addUser(badUser);
+      await tester.pumpWidget(
+         TestZulipApp(accountId: eg.selfAccount.id,
+          child: AvatarImage(userId: badUser.userId, size: 30)));
+      await tester.pumpAndSettle();
+      check(findPlaceholder).findsOne();
+      debugNetworkImageHttpClientProvider = null;
+    });
```
Comment (chrisbobbe) [inline test/widgets/user_test.dart]:
```suggestion
    testWidgets('shows placeholder when image URL gives error', (WidgetTester tester) async {
      addTearDown(testBinding.reset);
      prepareBoringImageHttpClient(success: false);
      await testBinding.globalStore.add(eg.selfAccount, eg.initialSnapshot());
      final store = await testBinding.globalStore.perAccount(eg.selfAccount.id);

      final badUser = eg.user(avatarUrl: 'https://zulip.com/avatarinvalid.png');
      await store.addUser(badUser);

      await tester.pumpWidget(
        TestZulipApp(accountId: eg.selfAccount.id,
          child: AvatarImage(userId: badUser.userId, size: 30)));
      await tester.pumpAndSettle();
      check(findPlaceholder).findsOne();

      debugNetworkImageHttpClientProvider = null;
    });
```

File: test/widgets/user_test.dart [hunk 19]
```diff
@@ -78,5 +83,48 @@ void main() {
...
+
+      final userWithNoUrl = eg.user(avatarUrl: null);
+      await store.addUser(userWithNoUrl);
+
+      await tester.pumpWidget(
+        TestZulipApp(accountId: eg.selfAccount.id,
+            child: AvatarImage(userId: userWithNoUrl.userId, size: 30)));
+      await tester.pumpAndSettle();
+      check(findPlaceholder).findsOne();
+    });
```
Comment (chrisbobbe) [inline test/widgets/user_test.dart]:
```suggestion
    testWidgets('shows placeholder when user avatarUrl is null', (WidgetTester tester) async {
      addTearDown(testBinding.reset);
      await testBinding.globalStore.add(eg.selfAccount, eg.initialSnapshot());
      final store = await testBinding.globalStore.perAccount(eg.selfAccount.id);

      final userWithNoUrl = eg.user(avatarUrl: null);
      await store.addUser(userWithNoUrl);

      await tester.pumpWidget(
        TestZulipApp(accountId: eg.selfAccount.id,
          child: AvatarImage(userId: userWithNoUrl.userId, size: 30)));
      await tester.pumpAndSettle();
      check(findPlaceholder).findsOne();
    });
```

File: test/widgets/user_test.dart [hunk 20]
```diff
@@ -78,5 +83,48 @@ void main() {
...
+      await testBinding.globalStore.add(eg.selfAccount, eg.initialSnapshot());
+
+      const nonExistentUserId = 9999999;
+
+      await tester.pumpWidget(
+       TestZulipApp(accountId: eg.selfAccount.id,
+            child: AvatarImage(userId: nonExistentUserId, size: 30)));
+      await tester.pumpAndSettle();
+      check(findPlaceholder).findsOne();
+    });
```
Comment (chrisbobbe) [inline test/widgets/user_test.dart]:
```suggestion
    testWidgets('shows placeholder when user is not found', (WidgetTester tester) async {
      addTearDown(testBinding.reset);
      await testBinding.globalStore.add(eg.selfAccount, eg.initialSnapshot());

      const nonExistentUserId = 9999999;

      await tester.pumpWidget(
        TestZulipApp(accountId: eg.selfAccount.id,
          child: AvatarImage(userId: nonExistentUserId, size: 30)));
      await tester.pumpAndSettle();
      check(findPlaceholder).findsOne();
    });
```

File: test/widgets/user_test.dart [hunk 21]
```diff
@@ -78,5 +83,51 @@ void main() {
...
+      prepareBoringImageHttpClient(success: false);
+      await testBinding.globalStore.add(eg.selfAccount, eg.initialSnapshot());
+      final store = await testBinding.globalStore.perAccount(eg.selfAccount.id);
+
+      final badUser = eg.user(avatarUrl: 'https://zulip.com/avatarinvalid.png');
+      await store.addUser(badUser);
+
+      await tester.pumpWidget(
+         TestZulipApp(accountId: eg.selfAccount.id,
+           child: AvatarImage(userId: badUser.userId, size: 30)));
```
Comment (chrisbobbe) [inline test/widgets/user_test.dart]: Part of https://github.com/zulip/zulip-flutter/pull/1882#discussion_r2548238195 still isn't done; bump:

```suggestion
      await tester.pumpWidget(
        TestZulipApp(accountId: eg.selfAccount.id,
          child: AvatarImage(userId: badUser.userId, size: 30)));
```

**Comment by chrisbobbe** [comment]
Thanks, LGTM; marking for Greg's review.

File: test/widgets/new_dm_sheet_test.dart [hunk 22]
```diff
@@ -254,17 +254,17 @@ void main() {
   });
 
   group('user selection', () {
-    void checkUserSelected(WidgetTester tester, User user, bool expected) {
-      final icon = tester.widget<Icon>(find.descendant(
-        of: findUserTile(user),
-        matching: find.byType(Icon)));
+      Finder findInUserTile(User user, Finder finder) => find.descendant(of: findUserTile(user), matching: finder);
```
Comment (gnprice) [inline test/widgets/new_dm_sheet_test.dart]: This is still wrongly indented. Chris already showed you how this should look; please reread more carefully the comment at https://github.com/zulip/zulip-flutter/pull/1882#discussion_r2548230190 .

Comment (gnprice) [inline test/widgets/new_dm_sheet_test.dart]: nit: separately, this is too wide: necessary information appears after 80 columns.

File: test/widgets/new_dm_sheet_test.dart [hunk 23]
```diff
@@ -254,17 +254,17 @@ void main() {
...
 
+    void checkUserSelected(WidgetTester tester, User user, bool expected) {
       if (expected) {
         check(findUserChip(user)).findsOne();
-        check(icon).icon.equals(ZulipIcons.check_circle_checked);
+        check(findInUserTile(user,find.byIcon(ZulipIcons.check_circle_checked))).findsOne();
+        check(findInUserTile(user,find.byIcon(ZulipIcons.check_circle_unchecked))).findsNothing();
```
Comment (gnprice) [inline test/widgets/new_dm_sheet_test.dart]: nit: similarly too wide. Also missing space after comma:
```suggestion
        check(findInUserTile(user, find.byIcon(ZulipIcons.check_circle_unchecked)))
          .findsNothing();
```

File: test/widgets/user_test.dart [hunk 24]
```diff
@@ -53,7 +58,7 @@ void main() {
       debugNetworkImageHttpClientProvider = null;
     });
 
-   testWidgets('absolute URL, larger size', (tester) async {
+    testWidgets('absolute URL, larger size', (tester) async {
       tester.view.devicePixelRatio = 2.5;
```
Comment (gnprice) [inline test/widgets/user_test.dart:64]: Please reread your commits before asking others to review them, and remove any changes that aren't doing something desired.

File: test/test_images.dart [hunk 25]
```diff
@@ -12,12 +13,18 @@ import 'package:flutter_test/flutter_test.dart';
...
-    ..statusCode = HttpStatus.ok
-    ..content = kSolidBlueAvatar;
+  if (success) {
+    httpClient.request.response
+      ..statusCode = HttpStatus.ok
+      ..content = kSolidBlueAvatar;
+  } else {
+    httpClient.request.response
+      ..statusCode = HttpStatus.notFound
+      ..content = Uint8List(0);
```
Comment (gnprice) [inline test/test_images.dart]: Hmm, this feels like more detail to me than is conveyed by "success: false". A test might care about the difference between HttpStatus.notFound (i.e. 404) and other ways a request might fail.

This also doesn't feel like it's within the scope of a *boring* image HTTP client, which is what this function's name calls for.

Let's instead do these steps explicitly at the one test that's using this option.

Comment (gnprice) [reply test/test_images.dart]: (If we did want to add this feature to this function, then one thing we would definitely need to do at a minimum is to update its dartdoc — the documentation needs to be kept accurate.)

Comment (gnprice) [inline test/test_images.dart]: Why does this use a `Uint8List`? The existing path here just uses a plain `List<int>`.

(You can tell before even getting to this line that something different is being used, because this diff adds an import `dart:typed_data` which this file didn't need before.)

File: test/widgets/user_test.dart [hunk 26]
```diff
@@ -78,5 +83,51 @@ void main() {
...
+      await store.addUser(userWithNoUrl);
+
+      await tester.pumpWidget(
+        TestZulipApp(accountId: eg.selfAccount.id,
+          child: AvatarImage(userId: userWithNoUrl.userId, size: 30)));
+      await tester.pumpAndSettle();
+      check(findPlaceholder).findsOne();
+    });
+
+    testWidgets('shows placeholder when user is not found', (WidgetTester tester) async {
```
Comment (gnprice) [inline test/widgets/user_test.dart]: nit: organize the tests in the same order as the code they're testing. This case comes before the other error cases in the implementation, so its test goes before the other error tests.

File: test/widgets/user_test.dart [hunk 27]
```diff
@@ -78,5 +83,51 @@ void main() {
...
+      addTearDown(testBinding.reset);
+      await testBinding.globalStore.add(eg.selfAccount, eg.initialSnapshot());
+
+      const nonExistentUserId = 9999999;
```
Comment (gnprice) [inline test/widgets/user_test.dart]: Does this user ID really not exist? Will it for sure never exist in this test?

Seems like it *probably* won't, but the reader of the test shouldn't have to wonder. You can insert a check verifying that it doesn't exist, to let the reader be sure.

File: test/widgets/user_test.dart [hunk 28]
```diff
@@ -78,5 +83,51 @@ void main() {
...
+
+      await tester.pumpWidget(
+        TestZulipApp(accountId: eg.selfAccount.id,
+          child: AvatarImage(userId: nonExistentUserId, size: 30)));
+      await tester.pumpAndSettle();
```
Comment (gnprice) [inline test/widgets/user_test.dart]: Avoid `pumpAndSettle`. See https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#avoid-using-pumpandsettle — or the API doc for `pumpAndSettle` itself.

File: test/widgets/user_test.dart [hunk 29]
```diff
@@ -78,5 +83,51 @@ void main() {
       check(await actualUrl(tester, avatarUrl)).isNull();
       debugNetworkImageHttpClientProvider = null;
     });
+
+    testWidgets('shows placeholder when image URL gives error', (WidgetTester tester) async {
```
Comment (gnprice) [inline test/widgets/user_test.dart]: nit: omit boring type
```suggestion
    testWidgets('shows placeholder when image URL gives error', (tester) async {
```

Note that the existing tests near this one all do the same.

**Review by gnprice — COMMENTED** [review]
Thanks; comments below.

One commit-message nit:

    Co-authored-by: Chris Bobbe <cbobbe@zulip.com>
    Co-authored-by:  Greg Price <greg@zulip.com>

Cut extra space after colon.

Separately: why am I listed as a co-author? I don't think I wrote any of these changes 🙂

**Comment by vinodsingh-dev-gsoc** [comment]
Got it, ! I’m diving into this issue right now. Will keep you posted on the progress!

**Comment by vinodsingh-dev-gsoc** [comment]
Thanks for the review @gnprice and @chrisbobbe! 
I've addressed all the feedbacks Ready for another look! 🙏

File: test/widgets/user_test.dart (hunk 24 above)
Comment (gnprice) [reply test/widgets/user_test.dart:64]: bump

File: test/widgets/user_test.dart [hunk 30]
```diff
@@ -78,5 +85,63 @@ void main() {
...
+    });
+
+    testWidgets('shows placeholder when image URL gives error', (tester) async {
+      addTearDown(testBinding.reset);
+
+      final httpClient = prepareBoringImageHttpClient();
+      httpClient.request.response
+        ..statusCode = HttpStatus.notFound
+        ..content = <int>[];
+
```
Comment (gnprice) [inline test/widgets/user_test.dart]: This is overriding all the details that make this HTTP client "boring". So instead of calling `prepareBoringImageHttpClient`, it's better to have explicitly here the two lines of that function that are actually still being used.

File: test/widgets/user_test.dart [hunk 31]
```diff
@@ -78,5 +85,63 @@ void main() {
       check(await actualUrl(tester, avatarUrl)).isNull();
       debugNetworkImageHttpClientProvider = null;
     });
+
+    testWidgets('shows placeholder when user is not found', (tester) async {
+      addTearDown(testBinding.reset);
+
+      await testBinding.globalStore.add(eg.selfAccount, eg.initialSnapshot());
+      final store = await testBinding.globalStore.perAccount(eg.selfAccount.id);
```
Comment (gnprice) [inline test/widgets/user_test.dart:92]: nit: use blank lines to group code into meaningful stanzas

Here, the `testBinding.globalStore` use is the reason we need the `addTearDown(testBinding.reset)`. So they should be joined together.

File: test/widgets/user_test.dart [hunk 32]
```diff
@@ -78,5 +85,63 @@ void main() {
...
+
+      final badUser = eg.user(avatarUrl: 'https://zulip.com/avatarinvalid.png');
+      await store.addUser(badUser);
+
+      await tester.pumpWidget(
+        TestZulipApp(accountId: eg.selfAccount.id,
+          child: AvatarImage(userId: badUser.userId, size: 30)));
+
+      await tester.pump();
+      await tester.pump();
```
Comment (gnprice) [inline test/widgets/user_test.dart:137]: Similarly, these `pump` calls are directly related to the `pumpWidget`.

File: test/widgets/user_test.dart [hunk 33]
```diff
@@ -78,5 +85,63 @@ void main() {
...
+
+      check(findPlaceholder).findsOne();
+      debugNetworkImageHttpClientProvider = null;
```
Comment (gnprice) [inline test/widgets/user_test.dart:140]: Conversely, this reset of `debugNetworkImageHttpClientProvider` is unrelated to the steps that just happened — it's needed because this is the end of the test case, and because earlier we set that variable. So:


```suggestion
      await tester.pumpWidget(
        TestZulipApp(accountId: eg.selfAccount.id,
          child: AvatarImage(userId: badUser.userId, size: 30)));
      await tester.pump();
      await tester.pump();
      check(findPlaceholder).findsOne();

      debugNetworkImageHttpClientProvider = null;
```

File: test/widgets/user_test.dart [hunk 34]
```diff
@@ -78,5 +85,63 @@ void main() {
...
+      await store.addUser(userWithNoUrl);
+
+      await tester.pumpWidget(
+        TestZulipApp(accountId: eg.selfAccount.id,
+          child: AvatarImage(userId: userWithNoUrl.userId, size: 30)));
+      await tester.pump();
+      check(findPlaceholder).findsOne();
+    });
+
+    testWidgets('shows placeholder when image URL gives error', (tester) async {
```
Comment (gnprice) [inline test/widgets/user_test.dart]: This name sounds to me like it's saying there's an error in the URL itself, like it fails to parse. Instead:
```suggestion
    testWidgets('shows placeholder when image fails to load', (tester) async {
```

**Comment by gnprice** [comment]
(Is this intended to be ready for review? Be sure to leave a comment saying so when it is; otherwise it's hard to tell from a quick look at the thread.)

**Comment by vinodsingh-dev-gsoc** [comment]
Yes, this is ready for review! I have completed the changes. Please let me know if any further adjustments are needed.

File: test/widgets/user_test.dart [hunk 35]
```diff
@@ -43,13 +50,15 @@ void main() {
       const avatarUrl = 'https://example/avatar.png';
       check(await actualUrl(tester, avatarUrl)).isNotNull()
         .asString.equals(avatarUrl);
+
       debugNetworkImageHttpClientProvider = null;
```
Comment (gnprice) [inline test/widgets/user_test.dart:53]: Why all these changes to unrelated tests?

File: test/widgets/user_test.dart [hunk 36]
```diff
@@ -70,13 +80,70 @@ void main() {
...
+
+      await tester.pumpWidget(
+        TestZulipApp(accountId: eg.selfAccount.id,
+          child: AvatarImage(userId: userWithNoUrl.userId, size: 30)));
+      await tester.pump();
+      check(findPlaceholder).findsOne();
+    });
+
+    testWidgets('shows placeholder when image fails to load', (tester) async {
+      addTearDown(testBinding.reset);
```
Comment (gnprice) [inline test/widgets/user_test.dart]: similar to https://github.com/zulip/zulip-flutter/pull/1882#discussion_r2692458427 : this line should go next to the line that makes it necessary

**Review by gnprice — COMMENTED** [review]
Thanks! Just small comments below.

**Comment by vinodsingh-dev-gsoc** [comment]
I have completed the changes. Please let me know if any further adjustments are needed.

**Comment by gnprice** [comment]
Thanks! Looks good; merging.

**Comment by vinodsingh-dev-gsoc** [comment]
Hi @gnprice, @chrisbobbe, and @alya,

Big thanks for all the help and guidance on my first merged commit! I really appreciate the feedback—it was a great learning experience.

I'm excited to keep contributing and will make sure my future PRs are even more polished. Ready for the next challenge! 

Best,
Vinod Singh
