### PR TITLE
lightbox: Prevent hero animation between message lists

### LINKED ISSUE #44: lightbox: Fix Hero when multiple images in one message have same URL
When you tap an image preview in a message, the Hero animation needs a "tag" that uniquely identifies the image on the route (i.e., among all other images in the message list).

Currently, `_LightboxHeroTag` fails to uniquely identify an image when there are multiple image previews with the same URL in a message. The effect is that there is no Hero animation, and an error is logged to the console:

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.

Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
In this case, multiple heroes had the following tag: […]
```

The bug is a bit tricky to reproduce: the open-lightbox-on-tap handler is on the image preview widget itself, not on the image link text, and (empirically) servers try to deduplicate image previews in a message with the same URL. Try something like this to thwart that deduplication:

```
[image](/user_uploads/2/fd/AogAK3meEt4GkXJaDvDXNwyy/image.png)
[image](https://chat.zulip.org/user_uploads/2/fd/AogAK3meEt4GkXJaDvDXNwyy/image.png)
```

This TODO on `_LightboxHeroTag` gives a recipe for a potential fix:

```dart
// TODO: Add index of the image preview in the message, to not break if
//   there are multiple image previews with the same URL in the same
//   message. Maybe keep `src`, so that on exit the lightbox image doesn't
//   fly to an image preview with a different URL, following a message edit
//   while the lightbox was open.
```

### LINKED ISSUE #930: Hero animation for images should run only to/from lightbox, not between message lists
When a message has an image and you tap the image to see it in the lightbox, we use a `Hero` widget to cause the image to animate from its old position and size in the message list to its new position and size in the lightbox, and to do the same in reverse when you navigate back.

Currently, though, our implementation of this causes those "hero" animations to happen also when you navigate from one message list to another that happens to contain the same image-bearing message. That doesn't make so much sense, and tends to look glitchy. It can look extra glitchy when the message is off screen either before or after the navigation (or even both), as spotted by @alexmv:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/Images.20have.20the.20wrong.20z-index/near/1932012

So we should fix that.

I think the way to implement this will be to augment the `tag` parameter we pass to `Hero` so that it identifies not only the message and the image within the message, but the message list the message is shown in.

### PR DESCRIPTION
**Pull request by lakshya1goel**
Fixes #930.
Fixes #44.

### Before

https://github.com/user-attachments/assets/37a832c2-87d6-4223-a47e-f5549fccfead

### After

https://github.com/user-attachments/assets/206af9a4-f487-49ad-adca-54faa70d5783

### CODE REVIEW

**Comment by gnprice** [comment]
Thanks! Chat thread here:
https://chat.zulip.org/#narrow/channel/516-mobile-dev-help/topic/Hero.20animation/near/2092791
with comments particularly on how to write a good test for this fix.

**Comment by lakshya1goel** [comment]
Hi @PIG208, PR is ready for a review now, PTAL, Thanks!

File: test/widgets/lightbox_test.dart [hunk 1]
```diff
@@ -558,4 +601,51 @@ void main() {
       check(platform.position).equals(position);
     });
   });
-}
+
+  group('LightboxHero', () {
+    testWidgets('no hero animation occurs between different message list pages for same image', (tester) async {
+      final channel = eg.stream(streamId: eg.defaultStreamMessageStreamId);
+      final message = eg.streamMessage(stream: channel,
+        contentMarkdown: ContentExample.spoilerHeaderHasImage.html, topic: 'test topic');
```
Comment (PIG208) [inline test/widgets/lightbox_test.dart:609]: nit: This example seems a bit too atypical. How about using something like `imageSingle` to replicate a message that a user is more likely to encounter.

File: test/widgets/lightbox_test.dart [hunk 2]
```diff
@@ -558,4 +601,51 @@ void main() {
...
+
+      final imageFinder = find.byType(RealmContentNetworkImage);
+      final initialImageRect = tester.getRect(imageFinder);
+
+      await tester.tap(imageFinder);
+      await tester.pump();
+      await tester.pump(const Duration(milliseconds: 150));
+
+      final imageInTransition = tester.getRect(imageFinder);
+      check(imageInTransition.top != initialImageRect.top).isTrue();
```
Comment (PIG208) [inline test/widgets/lightbox_test.dart:646]: nit: utilize checks API when possible:
```suggestion
      check(imageInTransition.top).not((it) => it.equals(initialImageRect.top));
```
same below

File: test/widgets/lightbox_test.dart [hunk 3]
```diff
@@ -558,4 +601,51 @@ void main() {
...
+      check(imageInTransition.left != initialImageRect.left).isTrue();
+      await tester.pumpAndSettle();
+    });
+  });
+}
```
Comment (PIG208) [inline test/widgets/lightbox_test.dart:651]: Need a newline at the end of the file.

File: test/widgets/lightbox_test.dart [hunk 4]
```diff
@@ -558,4 +601,51 @@ void main() {
...
+      await tester.tap(find.descendant(
+        of: find.byType(StreamMessageRecipientHeader),
+        matching: find.text('test topic')));
+      await tester.pump();
+      await tester.pump(const Duration(milliseconds: 150));
+
+      final imageInTransition = tester.getRect(imageFinder);
+      check(imageInTransition.top).equals(initialImageRect.top);
+      check(imageInTransition.left).equals(initialImageRect.left);
+      await tester.pumpAndSettle();
```
Comment (PIG208) [inline test/widgets/lightbox_test.dart:628]: Is this supposed to be mid transition time? While this works, I feel that it can miss bugs if the duration somehow changes.

We can have a while-loop that checks `tester.hasRunningAnimations`, which pumps repeatedly with a fixed duration, and repeats the check:

```suggestion

      int timeElapsed = 0;
      const interval = 50;
      while (timeElapsed < interval || tester.hasRunningAnimations) {
        final imageInTransition = tester.getRect(imageFinder);
        check(imageInTransition.top).equals(initialImageRect.top);
        check(imageInTransition.left).equals(initialImageRect.left);
        await tester.pump(const Duration(milliseconds: interval));
        timeElapsed += interval;
      }
      check(timeElapsed).isGreaterOrEqual(interval);
```

File: test/widgets/lightbox_test.dart [hunk 5]
```diff
@@ -197,6 +204,37 @@ class FakeVideoPlayerPlatform extends Fake
 void main() {
   TestZulipBinding.ensureInitialized();
 
+  late PerAccountStore store;
+  late FakeApiConnection connection;
+
+  Future<void> setupMessageListPage(WidgetTester tester, {
```
Comment (PIG208) [inline test/widgets/lightbox_test.dart:210]: Let's keep this helper close to where it is used in the 'LightBoxHero' group.

File: test/widgets/lightbox_test.dart [hunk 6]
```diff
@@ -197,6 +204,37 @@ class FakeVideoPlayerPlatform extends Fake
...
+    Narrow narrow = const CombinedFeedNarrow(),
+    List<Message>? messages,
+    List<ZulipStream>? streams,
```
Comment (PIG208) [inline test/widgets/lightbox_test.dart:213]: Because none of the two callers actually rely on having different messages/channels, it looks like we can remove these parameters. An advantage of keeping the helper close to where it's used is that we can more easily spot what properties the tests rely on.

For things that are constant to the tests (like the topic name, finders), we can have a shared local variable within the group.

File: test/widgets/lightbox_test.dart [hunk 7]
```diff
@@ -558,4 +601,51 @@ void main() {
...
+  group('LightboxHero', () {
+    testWidgets('no hero animation occurs between different message list pages for same image', (tester) async {
+      final channel = eg.stream(streamId: eg.defaultStreamMessageStreamId);
+      final message = eg.streamMessage(stream: channel,
+        contentMarkdown: ContentExample.spoilerHeaderHasImage.html, topic: 'test topic');
+      await setupMessageListPage(tester, narrow: const CombinedFeedNarrow(),
+        streams: [channel], messages: [message]);
+
+      connection.prepare(json:
+        eg.newestGetMessagesResult(foundOldest: true, messages: [message]).toJson());
```
Comment (PIG208) [inline test/widgets/lightbox_test.dart:614]: nit: move this to the line just before `tester.tap`, because it prepares an API response for that

**Review by PIG208 — COMMENTED** [review]
Thanks for fixing this! The approach looks fine to me. Left a comment on the implementation and some more on the tests.

File: test/widgets/lightbox_test.dart (hunk 4 above)
Comment (PIG208) [reply test/widgets/lightbox_test.dart:628]: Just saw the [CZO comment](https://chat.zulip.org/#narrow/channel/516-mobile-dev-help/topic/Hero.20animation/near/2095334)[#mobile-dev-help > Hero animation @ 💬](https://chat.zulip.org/#narrow/channel/516-mobile-dev-help/topic/Hero.20animation/near/2095334):

> In order to have that benefit, it's important to keep the two test cases similar to each other as far as possible. It should be easy for the reader to convince themself that the two tests are checking the same thing, and just expecting opposite outcomes.

I agree that having these two tests similar to each other does mitigate the concern of one of them not working properly. So it's probably also fine to leave them as-is. Either way, we should comment that the duration is specifically chosen such that we are in the middle of a hero animation (if there is one).

File: lib/widgets/lightbox.dart [hunk 8]
```diff
@@ -44,16 +46,18 @@ class LightboxHero extends StatelessWidget {
...
   final Message message;
   final Uri src;
   final Widget child;
+  final BuildContext pageContext;
 
   @override
   Widget build(BuildContext context) {
     return Hero(
-      tag: _LightboxHeroTag(messageId: message.id, src: src),
+      tag: _LightboxHeroTag(messageId: message.id, src: src, pageContext: pageContext),
```
[the remark this answers is not in the document]
Comment (lakshya1goel) [reply lib/widgets/lightbox.dart:60]: Things would go wrong since using PageRoot.contextOf(context) here would break the hero animation because the widget exists in two different page contexts simultaneously in the `MessageListPage` and the `lightbox`. By explicitly passing the source page's context (pageContext), we ensure both the source and destination heroes use the same context value in their tags, allowing Flutter to properly match them for the animation.

File: test/widgets/lightbox_test.dart [hunk 9]
```diff
@@ -207,14 +245,19 @@ void main() {
...
+      // 2. The PageRoot widget to provide context for Hero animations between
+      //    the message list and lightbox.
+      await tester.pumpWidget(PageRoot(
+        child: const ZulipApp()
+      ));
       await tester.pump();
       final navigator = await ZulipApp.navigator;
       unawaited(navigator.push(getImageLightboxRoute(
         accountId: eg.selfAccount.id,
+        pageContext: PageRoot.contextOf(navigator.context),
```
[the remark this answers is not in the document]
Comment (lakshya1goel) [reply test/widgets/lightbox_test.dart:260]: No, I think we can't skip passing `pageContext` because during the hero animation, the transitioning widget lives in Flutter's overlay layer outside our PageRoot hierarchy. The hero animation needs the same tag value at both ends (source and destination) to know which widgets to animate between, and since we can't get the PageRoot context during the transition, we must pass it explicitly.

File: lib/widgets/lightbox.dart (hunk 8 above)
[the remark this answers is not in the document]
Comment (PIG208) [reply lib/widgets/lightbox.dart:64]: Indeed. Thanks for the explanation.

**Comment by lakshya1goel** [comment]
Pushed the revision, PTAL @PIG208. Thanks!

File: test/widgets/lightbox_test.dart [hunk 10]
```diff
@@ -558,4 +571,77 @@ void main() {
...
     });
   });
+
+  group('LightboxHero', () {
+    late PerAccountStore store;
+    late FakeApiConnection connection;
+
+    final channel = eg.stream();
+    final message = eg.streamMessage(stream: channel,
+        contentMarkdown: ContentExample.imageSingle.html, topic: 'test topic');
```
Comment (PIG208) [inline test/widgets/lightbox_test.dart:581]: nit: indentation
```suggestion
    final message = eg.streamMessage(stream: channel,
      contentMarkdown: ContentExample.imageSingle.html, topic: 'test topic');
```

File: test/widgets/lightbox_test.dart [hunk 11]
```diff
@@ -558,4 +571,77 @@ void main() {
...
+
+    Future<void> setupMessageListPage(WidgetTester tester) async {
+      addTearDown(testBinding.reset);
+      final subscription = eg.subscription(channel);
+      await testBinding.globalStore.add(eg.selfAccount, eg.initialSnapshot(
+        streams: [channel], subscriptions: [subscription]));
+      store = await testBinding.globalStore.perAccount(eg.selfAccount.id);
+      connection = store.connection as FakeApiConnection;
+
+      await store.addUser(eg.selfUser);
```
Comment (PIG208) [inline test/widgets/lightbox_test.dart:591]: nit:
```suggestion
      await store.addUser(eg.selfUser);
```
because `store.addUser` is a part of the setup code stanza

File: lib/widgets/content.dart [hunk 12]
```diff
@@ -663,12 +665,14 @@ class MessageImage extends StatelessWidget {
           src: resolvedSrcUrl,
           thumbnailUrl: resolvedThumbnailUrl,
           originalWidth: node.originalWidth,
-          originalHeight: node.originalHeight));
+          originalHeight: node.originalHeight,
+          pageContext: pageContext));
```
Comment (PIG208) [inline lib/widgets/content.dart:669]: While testing this, I tried passing `context` to `pageContext` (and below), and it appears to work. Let's try this so that we don't need to rely on having a PageRoot.

**Review by PIG208 — COMMENTED** [review]
Thanks for the update! I found a place where we can potentially shake off the dependency on PageRoot. Let me know what you think!

**Comment by lakshya1goel** [comment]
Pushed the revision @PIG208, please have a look. Thanks!

**Comment by PIG208** [comment]
Thanks! I think because we are not using the context of `PageRoot`, there is probably a better name than `pageConext`. (Maybe `messageImageContext`?) Marking this for Greg's review.

File: test/widgets/lightbox_test.dart [hunk 13]
```diff
@@ -558,4 +566,76 @@ void main() {
...
+      await tester.tap(find.descendant(
+        of: find.byType(StreamMessageRecipientHeader),
+        matching: find.text('test topic')));
+      await tester.pump();
+      // Pump halfway through the hero animation duration (300ms)
+      await tester.pump(const Duration(milliseconds: 150));
+
+      final imageInTransition = tester.getRect(imageFinder);
+      check(imageInTransition).top.equals(initialImageRect.top);
+      check(imageInTransition).left.equals(initialImageRect.left);
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:616]: Given `imageFinder = find.byType(RealmContentNetworkImage).first`, this doesn't make an entirely convincing check that there isn't a hero animation going on. This effectively says that the original image is still the *first* RealmContentNetworkImage in the tree — but if there were a hero animation going on, there's no reason that necessarily has to be the first image in the tree. Maybe it comes later in the tree than the original image.

File: test/widgets/lightbox_test.dart [hunk 14]
```diff
@@ -558,4 +566,76 @@ void main() {
...
+      final initialImageRect = tester.getRect(imageFinder);
+
+      await tester.tap(imageFinder);
+      await tester.pump();
+      // Pump halfway through the hero animation duration (300ms)
+      await tester.pump(const Duration(milliseconds: 150));
+
+      final imageInTransition = tester.getRect(imageFinder);
+      check(imageInTransition).top.not((it) => it.equals(initialImageRect.top));
+      check(imageInTransition).left.not((it) => it.equals(initialImageRect.left));
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:636]: Similarly, this says that the first RealmContentNetworkImage in the tree isn't at the place the original image was. But
* there's the new route, the lightbox, which has a version of the image — maybe that's the first one in the tree now
* there's the old route, the message list, which may have a version of the image — and although right now that won't have moved, maybe in the future we'll use a different navigation transition here so that the old route moves away while the new one is moving in. Again maybe that's the first one in the tree now.

So this should get more specific about our expectations in order to be convincing that it wouldn't end up passing even in some future where we've broken the hero animation entirely.

**Review by gnprice — COMMENTED** [review]
Thanks @lakshya1goel for taking this on, and @PIG208 for the previous reviews! Comments below.

File: lib/widgets/lightbox.dart [hunk 15]
```diff
@@ -21,20 +21,26 @@ import 'store.dart';
 //   fly to an image preview with a different URL, following a message edit
 //   while the lightbox was open.
```
[the remark this answers is not in the document]
Comment (lakshya1goel) [reply lib/widgets/lightbox.dart:22]: I think the current implementation handles this scenario well. When a message is edited while its image is open in the lightbox, the behavior depends on whether the image URL changes:
- If the edit changes the image URL:
The Hero animation won't find a matching tag (because src is part of the tag and has changed)
It will gracefully fall back to a fade transition instead of attempting to animate to the wrong image
- If the edit doesn't change the image URL:
All three tag components (messageId, src, and messageImageContext) still match
The Hero animation will work normally

File: test/widgets/lightbox_test.dart [hunk 16]
```diff
@@ -300,6 +308,100 @@ void main() {
...
+      await tester.tap(find.descendant(
+        of: find.byType(StreamMessageRecipientHeader),
+        matching: find.text('test topic')));
+      await tester.pump();
+      // Pump halfway through the hero animation duration (300ms)
+      await tester.pump(const Duration(milliseconds: 150));
+
+      final imageInTransition = tester.getRect(imageFinder);
+      check(imageInTransition).top.equals(initialImageRect.top);
+      check(imageInTransition).left.equals(initialImageRect.left);
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:399]: This test is also less specific than the previous revision. In fact this one no longer tests anything about the hero animation at all: even if you edit the code so that the tags are completely defeated and the hero animation happens all the time:
```diff
   bool operator ==(Object other) {
-    return other is _LightboxHeroTag &&
-      other.messageId == messageId &&
-      other.src == src &&
-      other.messageImageContext == messageImageContext;
+    return true;
   }
 
   @override
-  int get hashCode => Object.hash('_LightboxHeroTag', messageId, src, messageImageContext);
+  int get hashCode => '_LightboxHeroTag'.hashCode;
```

this test still passes.

Like with the other test case, can you describe what condition this verifies is true, in terms that reflect what the user sees on the screen?

**Review by gnprice — COMMENTED** [review]
Thanks for the revision — comments below.

For detailed how-to discussion, let's use [#mobile-dev-help > Hero animation](https://chat.zulip.org/#narrow/channel/516-mobile-dev-help/topic/Hero.20animation/with/2117577), since Zulip will be better for discussion than GitHub is.

**Comment by gnprice** [comment]
Thanks! Chat thread here about the tests: [#mobile-dev-help > Hero animation @ 💬](https://chat.zulip.org/#narrow/channel/516-mobile-dev-help/topic/Hero.20animation/near/2131953)

File: test/widgets/lightbox_test.dart [hunk 17]
```diff
@@ -197,6 +204,152 @@ class FakeVideoPlayerPlatform extends Fake
...
+        .where((element) => (element.widget as Hero).tag == heroWidgetTag)
+        .where((element) => element.findAncestorWidgetOfExactType<InteractiveViewer>() == null);
+
+        final destinationHeroElement = tester.elementList(find.byType(Hero))
+        .where((element) => (element.widget as Hero).tag == heroWidgetTag)
+        .where((element) => element.findAncestorWidgetOfExactType<InteractiveViewer>() != null);
+
+        check(sourceHeroElement).isNotEmpty();
+        //without hero animation, destination hero element should not exist
+        check(destinationHeroElement).isEmpty();
```
[the remark this answers is not in the document]
Comment (gnprice) [reply test/widgets/lightbox_test.dart:346]: And more fundamentally: this test does not succeed at doing its job as a test.

The purpose of a test is so that we don't accidentally revert your change. If we do revert your change, the test should fail.

Here:
* Revert your change, but keep the new tests, with the command `git checkout @~ lib/`.
* A different test below needs to be tweaked so it still compiles: comment out the `messageImageContext: navigator.context,` in a call to `getImageLightboxRoute`.
* Run this test file: `flutter test test/widgets/lightbox_test.dart`.
* This test "no hero animation occurs between different message list pages for same image" still passes, even though in reality a hero animation now *does* occur between such pages.
* (And the other test "Hero animation occurs smoothly when opening lightbox from message list" also gets the wrong answer: that one fails, even though in reality the thing it's testing for still works. That's because of that test's use of the `key` that was artificially added for the test — which is a good illustration of why that's not a good way for that test to work.)

**Review by gnprice — COMMENTED** [review]
Thanks for the revision. This is closer, but there are still significant things that need to be changed before we can merge it.

In particular, this version still doesn't have a test that successfully exercises the issue this PR is meant to fix. See the last pair of comments below.

File: test/widgets/lightbox_test.dart [hunk 18]
```diff
@@ -197,6 +204,152 @@ class FakeVideoPlayerPlatform extends Fake
...
+        final positionChangeLeft = animatedFlightImagePosition.left - previousAnimatedPosition.left;
+        check(positionChangeTop.abs()).isLessThan(0.1*totalTopDistance);
+        check(positionChangeLeft.abs()).isLessThan(0.1*totalLeftDistance);
+
+        previousAnimatedPosition = animatedFlightImagePosition;
+      }
+
+      await tester.pumpAndSettle();
+
+      final lightBoxImageFinder = find.byKey(Key(message.id.toString()));
```
[the remark this answers is not in the document]
Comment (lakshya1goel) [reply test/widgets/lightbox_test.dart:292]: actually this was done because when I was finding the image using the src url it is finding two images , this could be due to generation of  source and destination hero image during hero animation , how could I uniquely find out the image element without key ?

**Comment by lakshya1goel** [comment]
Hi @gnprice, thanks for the detailed reviews so far. 
I have revised the implementation as:
- Removed the hero related implementation and focused purely on the image now. (Used that earlier to check that the animation is actually a hero animation, nevertheless). 
- Removed the key used for the identification of the image rather used the image src now. 
- Moreover, sorry for the 2nd test, now I have checked and verified that it is failing on reverting my changes and passing after the fix. 
- Resolved the other comments mentioned above.

PTAL and let me know if anything else is required.
Thanks!

File: lib/widgets/lightbox.dart [hunk 19]
```diff
@@ -21,39 +21,55 @@ import 'store.dart';
...
   final Message message;
+  final BuildContext messageImageContext;
   final Uri src;
   final Widget child;
 
   @override
   Widget build(BuildContext context) {
     return Hero(
-      tag: _LightboxHeroTag(messageId: message.id, src: src),
+      tag: _LightboxHeroTag(messageImageContext: messageImageContext, src: src),
```
Comment (gnprice) [inline lib/widgets/lightbox.dart:72]: Is the `message` field on this class used for anything after this change?

File: test/widgets/lightbox_test.dart [hunk 20]
```diff
@@ -197,6 +203,136 @@ class FakeVideoPlayerPlatform extends Fake
...
+      final heroAnimationDuration = const Duration(milliseconds: 300);
+      final steps = 150;
+      final stepDuration = heroAnimationDuration ~/ steps;
+      List<Rect> imagePositions = [];
+      for (int i = 1; i <= steps; i++) {
+        await tester.pump(stepDuration);
+
+        final imageFinder = find.byWidgetPredicate((widget) =>
+          widget is RealmContentNetworkImage && widget.src == imageSrcUrl
+        ).first;
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:323]: Why `.first`?

The purpose of this test is to check that there isn't an image animating around. What if there's one copy that's animating around, and another that's staying in the initial position? The one that stays in the initial position could very well happen to be the first one found in the tree, and then this test would wrongly pass.

File: test/widgets/lightbox_test.dart [hunk 21]
```diff
@@ -197,6 +203,136 @@ class FakeVideoPlayerPlatform extends Fake
...
+      for (final position in animatedPositions) {
+        final positionChangeTop = position.top - previousPosition.top;
+        final positionChangeLeft = position.left - previousPosition.left;
+        check(positionChangeTop.abs()).isLessThan(0.1 * totalTopDistance);
+        check(positionChangeLeft.abs()).isLessThan(0.1 * totalLeftDistance);
+        check(position).not((pos) => pos.equals(previousPosition));
+
+        previousPosition = position;
+      }
+      await tester.pumpAndSettle();
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:281]: If this is needed, that suggests that the animation isn't actually over when this test stops checking.

File: test/widgets/lightbox_test.dart [hunk 22]
```diff
@@ -197,6 +203,136 @@ class FakeVideoPlayerPlatform extends Fake
...
+        initialImagePosition.top - animatedPositions.last.top).abs();
+      final totalLeftDistance = (
+        initialImagePosition.left - animatedPositions.last.left).abs();
+
+      Rect previousPosition = initialImagePosition;
+      for (final position in animatedPositions) {
+        final positionChangeTop = position.top - previousPosition.top;
+        final positionChangeLeft = position.left - previousPosition.left;
+        check(positionChangeTop.abs()).isLessThan(0.1 * totalTopDistance);
+        check(positionChangeLeft.abs()).isLessThan(0.1 * totalLeftDistance);
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:276]: 10% of the distance traveled in the whole animation is quite a lot for a duration of 1/150th of the total duration.

We can measure this better by using the Pythagorean theorem to compute the overall distance moved in the two-dimensional plane, rather than looking at motion in each axis separately. That way if the start and end points happen to be close in one axis, this doesn't expect unreasonably tight bounds on how much the image might move in that axis during the animation.

Comment (gnprice) [inline test/widgets/lightbox_test.dart:276]: Instead of checking each of these separately in a loop against the same upper bound, it's better to compute the max across all the steps and then check the comparison of just that max against the upper bound.

That will have the same behavior as to whether the test passes or fails. But if it fails, it will give more informative output: it'll print the number from the one step where the image moved the most, instead of just the one that happened to come first out of the steps that were over the bound. That's especially helpful when picking what the bound should be.

File: test/widgets/lightbox_test.dart [hunk 23]
```diff
@@ -197,6 +203,136 @@ class FakeVideoPlayerPlatform extends Fake
...
+      final stepDuration = heroAnimationDuration ~/ steps;
+      List<Rect> animatedPositions = [];
+      for (int i = 1; i <= steps; i++) {
+        await tester.pump(stepDuration);
+
+        final animatedFlightImageFinder = find.byWidgetPredicate((widget) =>
+          widget is RealmContentNetworkImage && widget.src == imageSrcUrl
+        );
+        final animatedFlightImagePosition = tester.getRect(animatedFlightImageFinder);
+        animatedPositions.add(animatedFlightImagePosition);
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:263]: This can be simpler and shorter by inlining.

**Review by gnprice — COMMENTED** [review]
Thanks for the revision. This is significantly closer; some comments below.

File: test/widgets/lightbox_test.dart (hunk 20 above)
Comment (lakshya1goel) [reply test/widgets/lightbox_test.dart:323]: Here I am getting 2 exactly same images, I have checked the position of both the images inside the loop for 150 steps using the logs and the position is same for both the images for a particular step.
This is probably due to the navigation, on the press of back button the top most route is being popped and we are moving to the older route so at a particular instance we are having the image due to both of these routes.

File: lib/widgets/lightbox.dart (hunk 19 above)
Comment (lakshya1goel) [reply lib/widgets/lightbox.dart:72]: yeah, its not required now.

File: test/widgets/lightbox_test.dart (hunk 20 above)
Comment (gnprice) [reply test/widgets/lightbox_test.dart:323]: Yeah, that sounds like the behavior we expect to see here.

The job of a test is to convince a skeptical reader that the behavior we expect to see is the behavior that's actually happening (given that the test passes). So in particular this test should be written so that it rules out the possibility I described above, and other alternative possibilities of that flavor.

**Comment by gnprice** [comment]
Thanks for the revision. This looks good now, except that the test needs to be more specific as described in this subthread above: https://github.com/zulip/zulip-flutter/pull/1348#discussion_r2019569770

File: test/widgets/lightbox_test.dart [hunk 24]
```diff
@@ -197,6 +204,146 @@ class FakeVideoPlayerPlatform extends Fake
...
+        }
+      }
+
+      for (final element in imagePositionsOverTime.keys) {
+        final positions = imagePositionsOverTime[element]!;
+        check(positions).isNotEmpty();
+
+        final initialPos = positions[0];
+        for (final position in positions) {
+          check(position).equals(initialPos);
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:339]: This still isn't very specific, because it doesn't check that the set of elements at one step has any relationship to the set of elements at another step.

For example, one plausible buggy behavior would be that at each step, there's a new image element and the old image element is gone. From the user's perspective this could produce an animation, because the new element could be at a different position along an animation path. But that would pass this test, because each list would have just one entry in it.

Comment (gnprice) [reply test/widgets/lightbox_test.dart:339]: Instead, try this:
* Before navigating to the second page, find the one image element and remember its location.
* While on the second page, find the one image element that's now visible and remember its location.
* Once the animation starts, at each step, check that the set of image elements is exactly those two image elements.
* Also at each step, check that each image element is in the same place as it was at the start.

Does that pass? If so, great — that's very specific and makes clear what the behavior is.

If not, then loosen the conditions a little in order to make it pass. But experiment to find just how and why the specific version fails, so that you can loosen it in only the minimal way that makes it pass, keeping it as specific as possible.

**Comment by lakshya1goel** [comment]
Hi, @gnprice just pushed the revision following the comments above. The test is passing without loosening the constraints.
PTAL, Thanks!

File: test/widgets/lightbox_test.dart [hunk 25]
```diff
@@ -197,6 +204,153 @@ class FakeVideoPlayerPlatform extends Fake
...
+
+      for (int i = 0; i < steps; i++) {
+        await tester.pump(stepDuration);
+
+        final currentImages = find.byWidgetPredicate((widget) =>
+          widget is RealmContentNetworkImage && widget.src == imageSrcUrl).evaluate();
+        check(currentImages)
+          ..length.equals(2)
+          ..contains(firstElement)
+          ..contains(secondElement);
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:335]: Fun shorthand for this:
```suggestion
        check(currentImages).unorderedEquals([firstElement, secondElement]);
```

File: test/widgets/lightbox_test.dart [hunk 26]
```diff
@@ -197,6 +204,153 @@ class FakeVideoPlayerPlatform extends Fake
...
+      final steps = 150;
+      final stepDuration = heroAnimationDuration ~/ steps;
+      final firstImagePositions = <Rect>[];
+      final secondImagePositions = <Rect>[];
+
+      for (int i = 0; i < steps; i++) {
+        await tester.pump(stepDuration);
+
+        final currentImages = find.byWidgetPredicate((widget) =>
+          widget is RealmContentNetworkImage && widget.src == imageSrcUrl).evaluate();
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:331]: This is the same finder as `secondImageFinder`, right? It's really "find images with this URL". So it'd be good to combine them, under a name that reflects that shared meaning.

They can also replace `firstImageFinder`, if we just identify the URL in advance.

And we can do that, because this test controls what the URL is going to be — it set up the message list and supplied the message HTML.

Probably cleanest is to just duplicate the URL from that ContentExample value. It's unlikely to change; if it does change, the tests will fail because they won't find elements they expect. So like:
```dart
    final message = eg.streamMessage(stream: channel,
      contentMarkdown: ContentExample.imageSingle.html, topic: 'test topic');
    
    // From ContentExample.imageSingle.
    final imageSrcUrlStr = '/user_uploads/2/ce/nvoNL2LaZOciwGZ-FYagddtK/image.jpg';
    final imageSrcUrl = …;
    final imageFinder = …;
```

File: test/widgets/lightbox_test.dart [hunk 27]
```diff
@@ -197,6 +204,153 @@ class FakeVideoPlayerPlatform extends Fake
...
+      await tester.pumpAndSettle();
+
+      final secondImageFinder = find.byWidgetPredicate((widget) =>
+        widget is RealmContentNetworkImage && widget.src == imageSrcUrl
+      );
+      final secondImagePosition = tester.getRect(secondImageFinder);
+      final secondElement = secondImageFinder.evaluate().single;
+
+      final backButton = find.byType(BackButton);
+      await tester.tap(backButton);
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:318]: nit: simpler if inlined

File: test/widgets/lightbox_test.dart [hunk 28]
```diff
@@ -197,6 +204,153 @@ class FakeVideoPlayerPlatform extends Fake
...
+      final firstImagePosition = tester.getRect(firstImageFinder);
+      final firstElement = firstImageFinder.evaluate().single;
+
+      connection.prepare(json:
+        eg.newestGetMessagesResult(foundOldest: true, messages: [message]).toJson());
+
+      await tester.tap(find.descendant(
+        of: find.byType(StreamMessageRecipientHeader),
+        matching: find.text('test topic')));
+      await tester.pumpAndSettle();
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:309]: nit: these are logically one operation, so join as one stanza:
```suggestion
      connection.prepare(json:
        eg.newestGetMessagesResult(foundOldest: true, messages: [message]).toJson());
      await tester.tap(find.descendant(
        of: find.byType(StreamMessageRecipientHeader),
        matching: find.text('test topic')));
      await tester.pumpAndSettle();
```

File: test/widgets/lightbox_test.dart [hunk 29]
```diff
@@ -197,6 +204,153 @@ class FakeVideoPlayerPlatform extends Fake
...
+      final initialImagePosition = tester.getRect(messageListImageFinder);
+      await tester.tap(messageListImageFinder);
+      await tester.pump();
+      // pump to start hero animation
+      await tester.pump();
+
+      const heroAnimationDuration = Duration(milliseconds: 300);
+      const steps = 150;
+      final stepDuration = heroAnimationDuration ~/ steps;
+      List<Rect> animatedPositions = [];
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:256]: nit: final

File: test/widgets/lightbox_test.dart [hunk 30]
```diff
@@ -197,6 +204,153 @@ class FakeVideoPlayerPlatform extends Fake
 void main() {
   TestZulipBinding.ensureInitialized();
 
+  group('LightboxHero', () {
+    late PerAccountStore store;
+    late FakeApiConnection connection;
+
+    final channel = eg.stream();
+    final message = eg.streamMessage(stream: channel,
+      contentMarkdown: ContentExample.imageSingle.html, topic: 'test topic');
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:213]: nit: order elements logically: so stream, topic, then content, because the stream and topic give the more general context where the content appears

**Comment by lakshya1goel** [comment]
Hi, @gnprice I have pushed the revision. PTAL, Thanks!

File: test/widgets/lightbox_test.dart [hunk 31]
```diff
@@ -197,6 +204,128 @@ class FakeVideoPlayerPlatform extends Fake
 void main() {
   TestZulipBinding.ensureInitialized();
 
+  group('LightboxHero', () {
+    late PerAccountStore store;
+    late FakeApiConnection connection;
+
+    final channel = eg.stream();
+    final imageSrcUrlStr = 'https://chat.example/user_uploads/thumbnail/2/ce/nvoNL2LaZOciwGZ-FYagddtK/image.jpg/840x560.webp';
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:212]: nit: this should have a comment saying where it comes from, as it otherwise looks quite random — cf https://github.com/zulip/zulip-flutter/pull/1348#discussion_r2029628420

File: test/widgets/lightbox_test.dart (hunk 29 above)
Comment (gnprice) [reply test/widgets/lightbox_test.dart:256]: `const` (which is stronger than `final`) was fine for the locals where it applied — this comment was meant for `animatedPositions` :slightly_smiling_face: 

(In GitHub's review interface, if you make a comment targeting just a single line — like this one was — it shows the 4 lines up through that one as the context. That does makes it look a bit ambiguous, though in cases where the difference matters it is possible to find if you look closely: some comments say "Comment on lines MMM to NNN" above them.)

The principle here is that when a value is marked as immutable, that makes the code easier for the reader to reason about. So whenever we don't actually need to mutate it (like we do for loop variables like `previousPosition`), it's best to declare it `final` or `const`.

File: test/widgets/lightbox_test.dart [hunk 32]
```diff
@@ -197,6 +204,128 @@ class FakeVideoPlayerPlatform extends Fake
...
+      await setupMessageListPage(tester);
+
+      final messageContentFinder = find.byWidgetPredicate((widget) =>
+        widget is MessageContent && widget.message.id == message.id
+      );
+      final messageListImageFinder = find.descendant(
+        of: messageContentFinder,
+        matching: find.byType(RealmContentNetworkImage)
+      );
+      final initialImagePosition = tester.getRect(messageListImageFinder);
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:247]: This can be simplified to work the same way as the corresponding part of the other test case. (And then `imageFinder` can be shared between the test cases.)

File: test/widgets/lightbox_test.dart [hunk 33]
```diff
@@ -197,6 +204,128 @@ class FakeVideoPlayerPlatform extends Fake
...
+      final steps = 150;
+      final stepDuration = heroAnimationDuration ~/ steps;
+      for (int i = 0; i < steps; i++) {
+        await tester.pump(stepDuration);
+
+        final currentImages = imageFinder.evaluate();
+        check(currentImages).unorderedEquals([firstElement, secondElement]);
+
+        check(tester.getRect(
+          find.byElementPredicate((e) => e == firstElement))).equals(firstImagePosition);
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:320]: nit: line too long; instead:
```suggestion
        check(tester.getRect(find.byElementPredicate((e) => e == firstElement)))
          .equals(firstImagePosition);
```

File: test/widgets/lightbox_test.dart [hunk 34]
```diff
@@ -197,6 +204,128 @@ class FakeVideoPlayerPlatform extends Fake
...
+      await tester.pump();
+
+      final heroAnimationDuration = Duration(milliseconds: 300);
+      final steps = 150;
+      final stepDuration = heroAnimationDuration ~/ steps;
+      for (int i = 0; i < steps; i++) {
+        await tester.pump(stepDuration);
+
+        final currentImages = imageFinder.evaluate();
+        check(currentImages).unorderedEquals([firstElement, secondElement]);
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:317]: nit: simpler if inlined

File: test/widgets/lightbox_test.dart [hunk 35]
```diff
@@ -197,6 +204,128 @@ class FakeVideoPlayerPlatform extends Fake
...
+    testWidgets('no hero animation occurs between different message list pages for same image', (tester) async {
+      prepareBoringImageHttpClient();
+
+      await setupMessageListPage(tester);
+
+      final imageFinder = find.byWidgetPredicate((widget) =>
+        widget is RealmContentNetworkImage && widget.src == imageSrcUrl
+      );
+      final firstImagePosition = tester.getRect(imageFinder);
+      final firstElement = imageFinder.evaluate().single;
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:295]: Bit cleaner (as `evaluate` is meant really as internal API for implementing these finders):
```suggestion
      final firstElement = tester.element(imageFinder);
```

File: test/widgets/lightbox_test.dart (hunk 33 above)
Comment (gnprice) [reply test/widgets/lightbox_test.dart:320]: Better yet, make a little helper function within this test case, and then:
```suggestion
        check(getElementRect(firstElement)).equals(firstImagePosition);
```

Then the same `getElementRect` can be used for defining `firstImagePosition` in terms of `firstElement` in the first place. That way this check works the same way as `firstImagePosition` got computed originally — so we're doing the same thing the same way both times, instead of two somewhat different ways, and that means one fewer thing for the reader to understand and think through.

File: test/widgets/lightbox_test.dart [hunk 36]
```diff
@@ -197,6 +204,128 @@ class FakeVideoPlayerPlatform extends Fake
...
+      final totalDistance = sqrt(
+        pow(initialImagePosition.top - animatedPositions.last.top, 2) +
+        pow(initialImagePosition.left - animatedPositions.last.left, 2));
+
+      Rect previousPosition = initialImagePosition;
+      double maxStepDistance = 0.0;
+      for (final position in animatedPositions) {
+        final stepDistance = sqrt(
+          pow(position.top - previousPosition.top, 2) +
+          pow(position.left - previousPosition.left, 2));
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:275]: The logic here can become a bit easier to see by making a small helper function inside the test case:
```suggestion
        final stepDistance = dist(previousPosition, position);
```

Particularly for comparison with `totalDistance` above.

File: test/widgets/lightbox_test.dart [hunk 37]
```diff
@@ -197,6 +204,128 @@ class FakeVideoPlayerPlatform extends Fake
...
+      connection = store.connection as FakeApiConnection;
+      await store.addUser(eg.selfUser);
+
+      connection.prepare(json:
+        eg.newestGetMessagesResult(foundOldest: true, messages: [message]).toJson());
+
+      await tester.pumpWidget(TestZulipApp(accountId: eg.selfAccount.id,
+        child: MessageListPage(initNarrow: const CombinedFeedNarrow())));
+
+      await tester.pumpAndSettle();
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:232]: nit: these are basically one operation; join them as one stanza:
```suggestion

      connection.prepare(json:
        eg.newestGetMessagesResult(foundOldest: true, messages: [message]).toJson());
      await tester.pumpWidget(TestZulipApp(accountId: eg.selfAccount.id,
        child: MessageListPage(initNarrow: const CombinedFeedNarrow())));
      await tester.pumpAndSettle();
```

**Review by gnprice — COMMENTED** [review]
Thanks for the revision! This is getting closer; here's comments on this version.

(This review is a bit delayed because I was out sick part of last week.)

**Comment by lakshya1goel** [comment]
Hi, I have pushed the revision. PTAL @gnprice. Thanks!

File: test/widgets/lightbox_test.dart [hunk 38]
```diff
@@ -197,6 +204,112 @@ class FakeVideoPlayerPlatform extends Fake
...
+
+      await tester.tap(find.byType(BackButton));
+      await tester.pump();
+
+      const heroAnimationDuration = Duration(milliseconds: 300);
+      const steps = 150;
+      final stepDuration = heroAnimationDuration ~/ steps;
+      for (int i = 0; i < steps; i++) {
+        await tester.pump(stepDuration);
+        check(imageFinder.evaluate()).unorderedEquals([firstElement, secondElement]);
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:304]: nit: similar comment as: https://github.com/zulip/zulip-flutter/pull/1348#discussion_r2045447107

File: test/widgets/lightbox_test.dart [hunk 39]
```diff
@@ -197,6 +204,112 @@ class FakeVideoPlayerPlatform extends Fake
...
+
+    final channel = eg.stream();
+    // From ContentExample.imageSingle.
+    final imageSrcUrlStr = 'https://chat.example/user_uploads/thumbnail/2/ce/nvoNL2LaZOciwGZ-FYagddtK/image.jpg/840x560.webp';
+    final imageSrcUrl = Uri.parse(imageSrcUrlStr);
+    final message = eg.streamMessage(stream: channel,
+      topic: 'test topic', contentMarkdown: ContentExample.imageSingle.html);
+
+    final imageFinder = find.byWidgetPredicate(
+      (widget) => widget is RealmContentNetworkImage && widget.src == imageSrcUrl);
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:219]: nit: this is clearer if rearranged (like at https://github.com/zulip/zulip-flutter/pull/1348#discussion_r2029628420):
```suggestion
    final channel = eg.stream();
    final message = eg.streamMessage(stream: channel,
      topic: 'test topic', contentMarkdown: ContentExample.imageSingle.html);

    // From ContentExample.imageSingle.
    final imageSrcUrlStr = 'https://chat.example/user_uploads/thumbnail/2/ce/nvoNL2LaZOciwGZ-FYagddtK/image.jpg/840x560.webp';
    final imageSrcUrl = Uri.parse(imageSrcUrlStr);
    final imageFinder = find.byWidgetPredicate(
      (widget) => widget is RealmContentNetworkImage && widget.src == imageSrcUrl);
```

There's basically two narratives (or mini-narratives) here: setting up `message`, and setting up `imageFinder`. This way the reader gets through one, then goes through the other, rather than interleaving them.

This way also makes the comment on `imageSrcUrlStr` make more sense — the reason `ContentExample.imageSingle` is relevant is that it's what's used in `message`. When this comes shortly after `message` rather than before it, the reader has that context.

**Review by gnprice — COMMENTED** [review]
Thanks for the revision! Down now to a couple of small comments, both of them echoes of comments from the last round.

File: test/widgets/lightbox_test.dart [hunk 40]
```diff
@@ -197,6 +204,115 @@ class FakeVideoPlayerPlatform extends Fake
...
+
+      const heroAnimationDuration = Duration(milliseconds: 300);
+      const steps = 150;
+      final stepDuration = heroAnimationDuration ~/ steps;
+      for (int i = 0; i < steps; i++) {
+        await tester.pump(stepDuration);
+        check(tester.element(imageFinder.first)).anyOf([
+          (e) => e.equals(firstElement), (e) => e.equals(secondElement)]);
+        check(tester.element(imageFinder.last)).anyOf([
+          (e) => e.equals(firstElement), (e) => e.equals(secondElement)]);
```
Comment (gnprice) [inline test/widgets/lightbox_test.dart:307]: This no longer checks that the situation is the way we expect: it allows there to be three or more elements matching `imageFinder`.

It's also a lot more code to read than an `unorderedEquals` check. (Cf. my previous comment https://github.com/zulip/zulip-flutter/pull/1348#discussion_r2029614529 .)

Using `unorderedEquals` is the right way to do this. You'll want something different from `tester.element`, though.

Take a look around the API surrounding `tester.element` to see what variations of it you can find that would be useful here. I recommend jumping in your IDE to the definition of `tester.element` — that will let you browse around the neighboring code.

File: pubspec.lock [hunk 41]
```diff
@@ -650,26 +650,26 @@ packages:
     dependency: transitive
     description:
       name: leak_tracker
-      sha256: "6bb818ecbdffe216e81182c2f0714a2e62b593f4a4f13098713ff1685dfb6ab0"
+      sha256: "8dcda04c3fc16c14f48a7bb586d4be1f0d1572731b6d81d51772ef47c02081e0"
```
Comment (gnprice) [inline pubspec.lock:653]: This diff doesn't seem related to what this commit is doing. To keep the commits [clear and coherent](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html), this change should be kept to a separate commit.

It should also go with a corresponding change in `pubspec.yaml`. See our README about upgrading Flutter.

**Comment by lakshya1goel** [comment]
Hi @gnprice, I have pushed the correction please have a look. Thanks!

**Review by gnprice — COMMENTED** [review]
Thanks @lakshya1goel for all your work on this!

The tests all look good now, modulo one nit.

See also one more-substantive comment below. But I think it doesn't call for any code changes, only comments and metadata.

So I'll make those edits and merge. I'll also add a commit that revises the docs from this PR.

From reading the TODO comment that I remarked on in an earlier review, I see that this in fact fixes not only #930 but also another issue #44. A good followup for you would be to do next would be to write a regression test to ensure that #44 stays fixed; see details below.
