### PR TITLE
store: Pass `dont_block` in first poll attempt after a failure

### LINKED ISSUE #979: Loading indicator does not go away when the event queue appears to be active
We added a loading indicator in #852 that appears when even queue polling fails with any error.

However, it seems that the loading indicator can stay on even the event queue is doing fine, and does not go away until you get a new event.

I don't have a consistent way to reproduce this, but what I did was basically:

1. Leave the app on and lock the phone
2. After a while, unlock the phone
3. Observe if the loading indicator stays there longer than usual
4. Try to do something (like starring a message), and the loading indicator should go away promptly

My guess is that when the event queue goes stale, `isLoading` gets set to true. When we do get the new event queue, we do not set `isLoading` back to false.

### PR DESCRIPTION
**Pull request by chrisbobbe**
Fixes #979.

Discussion:
  https://github.com/zulip/zulip-flutter/issues/979#issuecomment-2993296322

------

Tested manually, with and without this change:

1. Log out from CZO (too active; events coming in frequently); connect to a not-very-active org

2. Make an artificial network error in the `getEvents` binding:

```diff
diff --git lib/api/route/events.dart lib/api/route/events.dart
index bd14521c7..da7bf4fea 100644
--- lib/api/route/events.dart
+++ lib/api/route/events.dart
@@ -1,6 +1,7 @@
 import 'package:json_annotation/json_annotation.dart';
 
 import '../core.dart';
+import '../exception.dart';
 import '../model/events.dart';
 import '../model/initial_snapshot.dart';
 
@@ -27,6 +28,7 @@ Future<InitialSnapshot> registerQueue(ApiConnection connection) {
 Future<GetEventsResult> getEvents(ApiConnection connection, {
   required String queueId, int? lastEventId, bool? dontBlock,
 }) {
+  throw NetworkException(routeName: 'foo', message: 'foo', cause: 'foo');
   return connection.get('getEvents', GetEventsResult.fromJson, 'events', {
     'queue_id': RawParameter(queueId),
     if (lastEventId != null) 'last_event_id': lastEventId,
```

3. Watch the logs to see retries going by
4. Comment out the `throw NetworkException` line and do a hot-reload
5. Watch the logs for `dont_block` in the `GET /events`, and watch the app to see if the loading indicator goes away quickly
   - Without the change, I don't see `dont_block`, and the loading indicator doesn't go away until the next event comes in
   - With the change, I see `dont_block`, and the loading indicator goes away quickly

### CODE REVIEW

**Comment by chrisbobbe** [comment]
I found a comment that needed updating; revision pushed.

File: test/model/store_test.dart [hunk 1]
```diff
@@ -1054,21 +1057,26 @@ void main() {
         return awaitFakeAsync((async) async {
           await prepare();
 
+          bool expectDontBlock = false; // (Not on the first attempt, but after that)
```
Comment (gnprice) [inline test/model/store_test.dart]: This is a bit confusing because of what I think is a double negative. This value takes effect precisely on the first attempt, right? Then it's set to a different value for the next attempt.

Comment (gnprice) [reply test/model/store_test.dart]: I think probably just dropping this comment clears things up. The reader can see a few lines below how this gets mutated after the first attempt.

Comment (chrisbobbe) [reply test/model/store_test.dart]: > This value takes effect precisely on the first attempt, right? Then it's set to a different value for the next attempt.

Yeah, that's right.

**Comment by chrisbobbe** [comment]
Thanks!! Revision pushed.

**Comment by gnprice** [comment]
Thanks! Looks good; merging.
